import strings from '../i18n/strings';

const GenderData = [
    {label: strings.male, value: 'male'},
    {label: strings.female, value: 'female'},
    {label: strings.other, value: 'other'},
  ];

const months = [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre'
  ];

const states = {
    "01": "AGUASCALIENTES",
    "02": "BAJA CALIFORNIA",
    "03": "BAJA CALIFORNIA SUR",
    "04": "CAMPECHE",
    "05": "COAHUILA",
    "06": "COLIMA",
    "07": "CHIAPAS",
    "08": "CHIHUAHUA",
    "09": "CIUDAD DE MEXICO",
    "10": "DURANGO",
    "11": "GUANAJUATO",
    "12": "GUERRERO",
    "13": "HIDALGO",
    "14": "JALISCO",
    "15": "MEXICO",
    "16": "MICHOACAN",
    "17": "MORELOS",
    "18": "NAYARIT",
    "19": "NUEVO LEON",
    "20": "OAXACA",
    "21": "PUEBLA",
    "22": "QUERETARO",
    "23": "QUINTANA ROO",
    "24": "SAN LUIS POTOSI",
    "25": "SINALOA",
    "26": "SONORA",
    "27": "TABASCO",
    "28": "TAMAULIPAS",
    "29": "TLAXCALA",
    "30": "VERACRUZ",
    "31": "YUCATAN",
    "32": "ZACATECAS"
};

const municipalities = {
    "01": {
      "001": "AGUASCALIENTES",
      "002": "ASIENTOS",
      "003": "CALVILLO",
      "004": "COSIO",
      "005": "JESUS MARIA",
      "006": "PABELLON DE ARTEAGA",
      "007": "RINCON DE ROMOS",
      "008": "SAN JOSE DE GRACIA",
      "009": "TEPEZALA",
      "010": "SAN FRANCISCO DE LOS ROMO",
      "011": "EL LLANO"
    },
    "02": {
      "001": "ENSENADA",
      "002": "MEXICALI",
      "003": "TECATE",
      "004": "TIJUANA",
      "005": "PLAYAS DE ROSARITO",
      "006": "SAN QUINTIN"
    },
    "03": {
      "001": "COMONDU",
      "002": "MULEGE",
      "003": "LA PAZ",
      "004": "LOS CABOS",
      "005": "LORETO"
    },
    "04": {
      "001": "CAMPECHE",
      "002": "CALKINI",
      "003": "CARMEN",
      "004": "CHAMPOTON",
      "005": "HECELCHAKAN",
      "006": "HOPELCHEN",
      "007": "PALIZADA",
      "008": "TENABO",
      "009": "ESCARCEGA",
      "010": "CANDELARIA",
      "011": "CALAKMUL",
      "012": "DZITBALCHE",
      "013": "SEYBAPLAYA"
    },
    "05": {
      "001": "ABASOLO",
      "002": "ACUÑA",
      "003": "ALLENDE",
      "004": "ARTEAGA",
      "005": "CANDELA",
      "006": "CASTAÑOS",
      "007": "CUATROCIENEGAS",
      "008": "ESCOBEDO",
      "009": "FRANCISCO I. MADERO",
      "010": "FRONTERA",
      "011": "GENERAL CEPEDA",
      "012": "GUERRERO",
      "013": "HIDALGO",
      "014": "JIMENEZ",
      "015": "JUAREZ",
      "016": "LAMADRID",
      "017": "MATAMOROS",
      "018": "MONCLOVA",
      "019": "MORELOS",
      "020": "MUZQUIZ",
      "021": "NADADORES",
      "022": "NAVA",
      "023": "OCAMPO",
      "024": "PARRAS",
      "025": "PIEDRAS NEGRAS",
      "026": "PROGRESO",
      "027": "RAMOS ARIZPE",
      "028": "SABINAS",
      "029": "SACRAMENTO",
      "030": "SALTILLO",
      "031": "SAN BUENAVENTURA",
      "032": "SAN JUAN DE SABINAS",
      "033": "SAN PEDRO",
      "034": "SIERRA MOJADA",
      "035": "TORREON",
      "036": "VIESCA",
      "037": "VILLA UNION",
      "038": "ZARAGOZA"
    },
    "06": {
      "001": "COLIMA",
      "002": "COMALA",
      "003": "COQUIMATLAN",
      "004": "CUAUHTEMOC",
      "005": "VILLA DE ALVAREZ",
      "006": "ARMERIA",
      "007": "IXTLAHUACAN",
      "008": "MANZANILLO",
      "009": "MINATITLAN",
      "010": "TECOMAN"
    },
    "07": {
      "001": "ACACOYAGUA",
      "002": "ACALA",
      "003": "ACAPETAHUA",
      "004": "ALTAMIRANO",
      "005": "AMATAN",
      "006": "AMATENANGO DE LA FRONTERA",
      "007": "AMATENANGO DEL VALLE",
      "008": "ANGEL ALBINO CORZO",
      "009": "ARRIAGA",
      "010": "BEJUCAL DE OCAMPO",
      "011": "BELLA VISTA",
      "012": "BERRIOZABAL",
      "013": "BOCHIL",
      "014": "EL BOSQUE",
      "015": "CACAHOATAN",
      "016": "CATAZAJA",
      "017": "CINTALAPA",
      "018": "COAPILLA",
      "019": "COMITAN DE DOMINGUEZ",
      "020": "LA CONCORDIA",
      "021": "COPAINALA",
      "022": "CHALCHIHUITAN",
      "023": "CHAMULA",
      "024": "CHANAL",
      "025": "CHAPULTENANGO",
      "026": "CHENALHO",
      "027": "CHIAPA DE CORZO",
      "028": "CHIAPILLA",
      "029": "CHICOASEN",
      "030": "CHICOMUSELO",
      "031": "CHILON",
      "032": "ESCUINTLA",
      "033": "FRANCISCO LEON",
      "034": "FRONTERA COMALAPA",
      "035": "FRONTERA HIDALGO",
      "036": "LA GRANDEZA",
      "037": "HUEHUETAN",
      "038": "HUITIUPAN",
      "039": "HUIXTAN",
      "040": "HUIXTLA",
      "041": "LA INDEPENDENCIA",
      "042": "IXHUATAN",
      "043": "IXTACOMITAN",
      "044": "IXTAPA",
      "045": "IXTAPANGAJOYA",
      "046": "JIQUIPILAS",
      "047": "JITOTOL",
      "048": "JUAREZ",
      "049": "LARRAINZAR",
      "050": "LA LIBERTAD",
      "051": "MAPASTEPEC",
      "052": "LAS MARGARITAS",
      "053": "MAZAPA DE MADERO",
      "054": "MAZATAN",
      "055": "METAPA",
      "056": "MITONTIC",
      "057": "MOTOZINTLA",
      "058": "NICOLAS RUIZ",
      "059": "OCOSINGO",
      "060": "OCOTEPEC",
      "061": "OCOZOCOAUTLA DE ESPINOSA",
      "062": "OSTUACAN",
      "063": "OSUMACINTA",
      "064": "OXCHUC",
      "065": "PALENQUE",
      "066": "PANTELHO",
      "067": "PANTEPEC",
      "068": "PICHUCALCO",
      "069": "PIJIJIAPAN",
      "070": "EL PORVENIR",
      "071": "PUEBLO NUEVO SOLISTAHUACAN",
      "072": "RAYON",
      "073": "REFORMA",
      "074": "LAS ROSAS",
      "075": "SABANILLA",
      "076": "SALTO DE AGUA",
      "077": "SAN CRISTOBAL DE LAS CASAS",
      "078": "SAN FERNANDO",
      "079": "SAN JUAN CANCUC",
      "080": "SAN LUCAS",
      "081": "SILTEPEC",
      "082": "SIMOJOVEL",
      "083": "SITALA",
      "084": "SOCOLTENANGO",
      "085": "SOLOSUCHIAPA",
      "086": "SOYALO",
      "087": "SUCHIAPA",
      "088": "SUCHIATE",
      "089": "SUNUAPA",
      "090": "TAPACHULA",
      "091": "TAPALAPA",
      "092": "TAPILULA",
      "093": "TECPATAN",
      "094": "TENEJAPA",
      "095": "TEOPISCA",
      "096": "TILA",
      "097": "TONALA",
      "098": "TOTOLAPA",
      "099": "LA TRINITARIA",
      "100": "TUMBALA",
      "101": "TUXTLA CHICO",
      "102": "TUXTLA GUTIERREZ",
      "103": "TUZANTAN",
      "104": "TZIMOL",
      "105": "UNION JUAREZ",
      "106": "VENUSTIANO CARRANZA",
      "107": "VILLACOMALTITLAN",
      "108": "VILLA CORZO",
      "109": "VILLAFLORES",
      "110": "YAJALON",
      "111": "ZINACANTAN",
      "112": "ALDAMA",
      "113": "BENEMERITO DE LAS AMERICAS",
      "114": "MARAVILLA TENEJAPA",
      "115": "MARQUES DE COMILLAS",
      "116": "MONTECRISTO DE GUERRERO",
      "117": "SAN ANDRES DURAZNAL",
      "118": "SANTIAGO EL PINAR",
      "119": "CAPITAN LUIS ANGEL VIDAL",
      "120": "RINCON CHAMULA SAN PEDRO",
      "121": "EL PARRAL",
      "122": "EMILIANO ZAPATA",
      "123": "MEZCALAPA",
      "124": "HONDURAS DE LA SIERRA"
    },
    "08": {
      "001": "AHUMADA",
      "002": "ALDAMA",
      "003": "ALLENDE",
      "004": "AQUILES SERDAN",
      "005": "ASCENSION",
      "006": "BACHINIVA",
      "007": "BALLEZA",
      "008": "BATOPILAS DE MANUEL GOMEZ MORIN",
      "009": "BOCOYNA",
      "010": "BUENAVENTURA",
      "011": "CAMARGO",
      "012": "CARICHI",
      "013": "CASAS GRANDES",
      "014": "CORONADO",
      "015": "COYAME DEL SOTOL",
      "016": "LA CRUZ",
      "017": "CUAUHTEMOC",
      "018": "CUSIHUIRIACHI",
      "019": "CHIHUAHUA",
      "020": "CHINIPAS",
      "021": "DELICIAS",
      "022": "DR. BELISARIO DOMINGUEZ",
      "023": "GALEANA",
      "024": "SANTA ISABEL",
      "025": "GOMEZ FARIAS",
      "026": "GRAN MORELOS",
      "027": "GUACHOCHI",
      "028": "GUADALUPE",
      "029": "GUADALUPE Y CALVO",
      "030": "GUAZAPARES",
      "031": "GUERRERO",
      "032": "HIDALGO DEL PARRAL",
      "033": "HUEJOTITAN",
      "034": "IGNACIO ZARAGOZA",
      "035": "JANOS",
      "036": "JIMENEZ",
      "037": "JUAREZ",
      "038": "JULIMES",
      "039": "LOPEZ",
      "040": "MADERA",
      "041": "MAGUARICHI",
      "042": "MANUEL BENAVIDES",
      "043": "MATACHI",
      "044": "MATAMOROS",
      "045": "MEOQUI",
      "046": "MORELOS",
      "047": "MORIS",
      "048": "NAMIQUIPA",
      "049": "NONOAVA",
      "050": "NUEVO CASAS GRANDES",
      "051": "OCAMPO",
      "052": "OJINAGA",
      "053": "PRAXEDIS G. GUERRERO",
      "054": "RIVA PALACIO",
      "055": "ROSALES",
      "056": "ROSARIO",
      "057": "SAN FRANCISCO DE BORJA",
      "058": "SAN FRANCISCO DE CONCHOS",
      "059": "SAN FRANCISCO DEL ORO",
      "060": "SANTA BARBARA",
      "061": "SATEVO",
      "062": "SAUCILLO",
      "063": "TEMOSACHIC",
      "064": "EL TULE",
      "065": "URIQUE",
      "066": "URUACHI",
      "067": "VALLE DE ZARAGOZA"
    },
    "09": {
      "002": "AZCAPOTZALCO",
      "003": "COYOACAN",
      "004": "CUAJIMALPA DE MORELOS",
      "005": "GUSTAVO A. MADERO",
      "006": "IZTACALCO",
      "007": "IZTAPALAPA",
      "008": "LA MAGDALENA CONTRERAS",
      "009": "MILPA ALTA",
      "010": "ALVARO OBREGON",
      "011": "TLAHUAC",
      "012": "TLALPAN",
      "013": "XOCHIMILCO",
      "014": "BENITO JUAREZ",
      "015": "CUAUHTEMOC",
      "016": "MIGUEL HIDALGO",
      "017": "VENUSTIANO CARRANZA"
    },
    "10": {
      "001": "CANATLAN",
      "002": "CANELAS",
      "003": "CONETO DE COMONFORT",
      "004": "CUENCAME",
      "005": "DURANGO",
      "006": "SIMON BOLIVAR",
      "007": "GOMEZ PALACIO",
      "008": "GUADALUPE VICTORIA",
      "009": "GUANACEVI",
      "010": "HIDALGO",
      "011": "INDE",
      "012": "LERDO",
      "013": "MAPIMI",
      "014": "MEZQUITAL",
      "015": "NAZAS",
      "016": "NOMBRE DE DIOS",
      "017": "NUEVO IDEAL",
      "018": "OCAMPO",
      "019": "EL ORO",
      "020": "OTAEZ",
      "021": "PANUCO DE CORONADO",
      "022": "PEÑON BLANCO",
      "023": "POANAS",
      "024": "PUEBLO NUEVO",
      "025": "RODEO",
      "026": "SAN BERNARDO",
      "027": "SAN DIMAS",
      "028": "SAN JUAN DE GUADALUPE",
      "029": "SAN JUAN DEL RIO",
      "030": "SAN LUIS DEL CORDERO",
      "031": "SAN PEDRO DEL GALLO",
      "032": "SANTA CLARA",
      "033": "SANTIAGO PAPASQUIARO",
      "034": "SUCHIL",
      "035": "TAMAZULA",
      "036": "TEPEHUANES",
      "037": "TLAHUALILO",
      "038": "TOPIA",
      "039": "VICENTE GUERRERO"
    },
    "11": {
      "001": "ABASOLO",
      "002": "ACAMBARO",
      "003": "SAN MIGUEL DE ALLENDE",
      "004": "APASEO EL ALTO",
      "005": "APASEO EL GRANDE",
      "006": "ATARJEA",
      "007": "CELAYA",
      "008": "MANUEL DOBLADO",
      "009": "COMONFORT",
      "010": "CORONEO",
      "011": "CORTAZAR",
      "012": "CUERAMARO",
      "013": "DOCTOR MORA",
      "014": "DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL",
      "015": "GUANAJUATO",
      "016": "HUANIMARO",
      "017": "IRAPUATO",
      "018": "JARAL DEL PROGRESO",
      "019": "JERECUARO",
      "020": "LEON",
      "021": "MOROLEON",
      "022": "OCAMPO",
      "023": "PENJAMO",
      "024": "PUEBLO NUEVO",
      "025": "PURISIMA DEL RINCON",
      "026": "ROMITA",
      "027": "SALAMANCA",
      "028": "SALVATIERRA",
      "029": "SAN DIEGO DE LA UNION",
      "030": "SAN FELIPE",
      "031": "SAN FRANCISCO DEL RINCON",
      "032": "SAN JOSE ITURBIDE",
      "033": "SAN LUIS DE LA PAZ",
      "034": "SANTA CATARINA",
      "035": "SANTA CRUZ DE JUVENTINO ROSAS",
      "036": "SANTIAGO MARAVATIO",
      "037": "SILAO DE LA VICTORIA",
      "038": "TARANDACUAO",
      "039": "TARIMORO",
      "040": "TIERRA BLANCA",
      "041": "URIANGATO",
      "042": "VALLE DE SANTIAGO",
      "043": "VICTORIA",
      "044": "VILLAGRAN",
      "045": "XICHU",
      "046": "YURIRIA"
    },
    "12": {
      "001": "ACAPULCO DE JUAREZ",
      "002": "AHUACUOTZINGO",
      "003": "AJUCHITLAN DEL PROGRESO",
      "004": "ALCOZAUCA DE GUERRERO",
      "005": "ALPOYECA",
      "006": "APAXTLA",
      "007": "ARCELIA",
      "008": "ATENANGO DEL RIO",
      "009": "ATLAMAJALCINGO DEL MONTE",
      "010": "ATLIXTAC",
      "011": "ATOYAC DE ALVAREZ",
      "012": "AYUTLA DE LOS LIBRES",
      "013": "AZOYU",
      "014": "BENITO JUAREZ",
      "015": "BUENAVISTA DE CUELLAR",
      "016": "COAHUAYUTLA DE JOSE MARIA IZAZAGA",
      "017": "COCULA",
      "018": "COPALA",
      "019": "COPALILLO",
      "020": "COPANATOYAC",
      "021": "COYUCA DE BENITEZ",
      "022": "COYUCA DE CATALAN",
      "023": "CUAJINICUILAPA",
      "024": "CUALAC",
      "025": "CUAUTEPEC",
      "026": "CUETZALA DEL PROGRESO",
      "027": "CUTZAMALA DE PINZON",
      "028": "CHILAPA DE ALVAREZ",
      "029": "CHILPANCINGO DE LOS BRAVO",
      "030": "EDUARDO NERI",
      "031": "FLORENCIO VILLARREAL",
      "032": "GENERAL CANUTO A. NERI",
      "033": "GENERAL HELIODORO CASTILLO",
      "034": "HUAMUXTITLAN",
      "035": "HUITZUCO DE LOS FIGUEROA",
      "036": "IGUALA DE LA INDEPENDENCIA",
      "037": "IGUALAPA",
      "038": "IXCATEOPAN DE CUAUHTEMOC",
      "039": "ZIHUATANEJO DE AZUETA",
      "040": "JUAN R. ESCUDERO",
      "041": "LEONARDO BRAVO",
      "042": "MALINALTEPEC",
      "043": "MARTIR DE CUILAPAN",
      "044": "METLATONOC",
      "045": "MOCHITLAN",
      "046": "OLINALA",
      "047": "OMETEPEC",
      "048": "PEDRO ASCENCIO ALQUISIRAS",
      "049": "PETATLAN",
      "050": "PILCAYA",
      "051": "PUNGARABATO",
      "052": "QUECHULTENANGO",
      "053": "SAN LUIS ACATLAN",
      "054": "SAN MARCOS",
      "055": "SAN MIGUEL TOTOLAPAN",
      "056": "TAXCO DE ALARCON",
      "057": "TECOANAPA",
      "058": "TECPAN DE GALEANA",
      "059": "TELOLOAPAN",
      "060": "TEPECOACUILCO DE TRUJANO",
      "061": "TETIPAC",
      "062": "TIXTLA DE GUERRERO",
      "063": "TLACOACHISTLAHUACA",
      "064": "TLACOAPA",
      "065": "TLALCHAPA",
      "066": "TLALIXTAQUILLA DE MALDONADO",
      "067": "TLAPA DE COMONFORT",
      "068": "TLAPEHUALA",
      "069": "LA UNION DE ISIDORO MONTES DE OCA",
      "070": "XALPATLAHUAC",
      "071": "XOCHIHUEHUETLAN",
      "072": "XOCHISTLAHUACA",
      "073": "ZAPOTITLAN TABLAS",
      "074": "ZIRANDARO",
      "075": "ZITLALA",
      "076": "ACATEPEC",
      "077": "JOSE JOAQUIN DE HERRERA",
      "078": "ILIATENCO",
      "079": "COCHOAPA EL GRANDE",
      "080": "MARQUELIA",
      "081": "JUCHITAN"
    },
    "13": {
      "001": "ACATLAN",
      "002": "ACAXOCHITLAN",
      "003": "ACTOPAN",
      "004": "AGUA BLANCA DE ITURBIDE",
      "005": "AJACUBA",
      "006": "ALFAJAYUCAN",
      "007": "ALMOLOYA",
      "008": "APAN",
      "009": "ATITALAQUIA",
      "010": "ATLAPEXCO",
      "011": "ATOTONILCO EL GRANDE",
      "012": "ATOTONILCO DE TULA",
      "013": "CALNALI",
      "014": "CARDONAL",
      "015": "CUAUTEPEC DE HINOJOSA",
      "016": "CHAPANTONGO",
      "017": "CHAPULHUACAN",
      "018": "CHILCUAUTLA",
      "019": "EL ARENAL",
      "020": "ELOXOCHITLAN",
      "021": "EMILIANO ZAPATA",
      "022": "EPAZOYUCAN",
      "023": "FRANCISCO I. MADERO",
      "024": "HUASCA DE OCAMPO",
      "025": "HUAUTLA",
      "026": "HUAZALINGO",
      "027": "HUEHUETLA",
      "028": "HUEJUTLA DE REYES",
      "029": "HUICHAPAN",
      "030": "IXMIQUILPAN",
      "031": "JACALA DE LEDEZMA",
      "032": "JALTOCAN",
      "033": "JUAREZ HIDALGO",
      "034": "LA MISION",
      "035": "LOLOTLA",
      "036": "METEPEC",
      "037": "METZTITLAN",
      "038": "MINERAL DEL CHICO",
      "039": "MINERAL DEL MONTE",
      "040": "MINERAL DE LA REFORMA",
      "041": "MIXQUIAHUALA DE JUAREZ",
      "042": "MOLANGO DE ESCAMILLA",
      "043": "NICOLAS FLORES",
      "044": "NOPALA DE VILLAGRAN",
      "045": "OMITLAN DE JUAREZ",
      "046": "PACULA",
      "047": "PACHUCA DE SOTO",
      "048": "PISAFLORES",
      "049": "PROGRESO DE OBREGON",
      "050": "SAN AGUSTIN METZQUITITLAN",
      "051": "SAN AGUSTIN TLAXIACA",
      "052": "SAN BARTOLO TUTOTEPEC",
      "053": "SAN FELIPE ORIZATLAN",
      "054": "SAN SALVADOR",
      "055": "SANTIAGO DE ANAYA",
      "056": "SANTIAGO TULANTEPEC DE LUGO GUERRERO",
      "057": "SINGUILUCAN",
      "058": "TASQUILLO",
      "059": "TECOZAUTLA",
      "060": "TENANGO DE DORIA",
      "061": "TEPEAPULCO",
      "062": "TEPEHUACAN DE GUERRERO",
      "063": "TEPEJI DEL RIO DE OCAMPO",
      "064": "TEPETITLAN",
      "065": "TETEPANGO",
      "066": "TEZONTEPEC DE ALDAMA",
      "067": "TIANGUISTENGO",
      "068": "TIZAYUCA",
      "069": "TLAHUELILPAN",
      "070": "TLAHUILTEPA",
      "071": "TLANALAPA",
      "072": "TLANCHINOL",
      "073": "TLAXCOAPAN",
      "074": "TOLCAYUCA",
      "075": "TULA DE ALLENDE",
      "076": "TULANCINGO DE BRAVO",
      "077": "VILLA DE TEZONTEPEC",
      "078": "XOCHIATIPAN",
      "079": "XOCHICOATLAN",
      "080": "YAHUALICA",
      "081": "ZACUALTIPAN DE ANGELES",
      "082": "ZAPOTLAN DE JUAREZ",
      "083": "ZEMPOALA",
      "084": "ZIMAPAN"
    },
    "14": {
      "001": "ACATIC",
      "002": "ACATLAN DE JUAREZ",
      "003": "AHUALULCO DE MERCADO",
      "004": "AMACUECA",
      "005": "AMATITAN",
      "006": "AMECA",
      "007": "SAN JUANITO DE ESCOBEDO",
      "008": "ARANDAS",
      "009": "EL ARENAL",
      "010": "ATEMAJAC DE BRIZUELA",
      "011": "ATENGO",
      "012": "ATENGUILLO",
      "013": "ATOTONILCO EL ALTO",
      "014": "ATOYAC",
      "015": "AUTLAN DE NAVARRO",
      "016": "AYOTLAN",
      "017": "AYUTLA",
      "018": "LA BARCA",
      "019": "BOLAÑOS",
      "020": "CABO CORRIENTES",
      "021": "CASIMIRO CASTILLO",
      "022": "CIHUATLAN",
      "023": "ZAPOTLAN EL GRANDE",
      "024": "SAN GABRIEL",
      "025": "COCULA",
      "026": "COLOTLAN",
      "027": "CONCEPCION DE BUENOS AIRES",
      "028": "CUAUTITLAN DE GARCIA BARRAGAN",
      "029": "CUAUTLA",
      "030": "CUQUIO",
      "031": "CHAPALA",
      "032": "CHIMALTITAN",
      "033": "CHIQUILISTLAN",
      "034": "DEGOLLADO",
      "035": "EJUTLA",
      "036": "ENCARNACION DE DIAZ",
      "037": "ETZATLAN",
      "038": "GOMEZ FARIAS",
      "039": "EL GRULLO",
      "040": "GUACHINANGO",
      "041": "GUADALAJARA",
      "042": "HOSTOTIPAQUILLO",
      "043": "HUEJUCAR",
      "044": "HUEJUQUILLA EL ALTO",
      "045": "LA HUERTA",
      "046": "IXTLAHUACAN DE LOS MEMBRILLOS",
      "047": "IXTLAHUACAN DEL RIO",
      "048": "JALOSTOTITLAN",
      "049": "JAMAY",
      "050": "JESUS MARIA",
      "051": "JILOTLAN DE LOS DOLORES",
      "052": "JOCOTEPEC",
      "053": "JUANACATLAN",
      "054": "JUCHITLAN",
      "055": "LAGOS DE MORENO",
      "056": "EL LIMON",
      "057": "MAGDALENA",
      "058": "SANTA MARIA DEL ORO",
      "059": "LA MANZANILLA DE LA PAZ",
      "060": "MASCOTA",
      "061": "MAZAMITLA",
      "062": "MEXTICACAN",
      "063": "MEZQUITIC",
      "064": "MIXTLAN",
      "065": "OCOTLAN",
      "066": "OJUELOS DE JALISCO",
      "067": "PIHUAMO",
      "068": "PONCITLAN",
      "069": "PUERTO VALLARTA",
      "070": "VILLA PURIFICACION",
      "071": "QUITUPAN",
      "072": "EL SALTO",
      "073": "SAN CRISTOBAL DE LA BARRANCA",
      "074": "SAN DIEGO DE ALEJANDRIA",
      "075": "SAN JUAN DE LOS LAGOS",
      "076": "SAN JULIAN",
      "077": "SAN MARCOS",
      "078": "SAN MARTIN DE BOLAÑOS",
      "079": "SAN MARTIN HIDALGO",
      "080": "SAN MIGUEL EL ALTO",
      "081": "SAN SEBASTIAN DEL OESTE",
      "082": "SANTA MARIA DE LOS ANGELES",
      "083": "SAYULA",
      "084": "TALA",
      "085": "TALPA DE ALLENDE",
      "086": "TAMAZULA DE GORDIANO",
      "087": "TAPALPA",
      "088": "TECALITLAN",
      "089": "TECOLOTLAN",
      "090": "TECHALUTA DE MONTENEGRO",
      "091": "TENAMAXTLAN",
      "092": "TEOCALTICHE",
      "093": "TEOCUITATLAN DE CORONA",
      "094": "TEPATITLAN DE MORELOS",
      "095": "TEQUILA",
      "096": "TEUCHITLAN",
      "097": "TIZAPAN EL ALTO",
      "098": "TLAJOMULCO DE ZUÑIGA",
      "099": "SAN PEDRO TLAQUEPAQUE",
      "100": "TOLIMAN",
      "101": "TOMATLAN",
      "102": "TONALA",
      "103": "TONAYA",
      "104": "TONILA",
      "105": "TOTATICHE",
      "106": "TOTOTLAN",
      "107": "TUXCACUESCO",
      "108": "TUXCUECA",
      "109": "TUXPAN",
      "110": "UNION DE SAN ANTONIO",
      "111": "UNION DE TULA",
      "112": "VALLE DE GUADALUPE",
      "113": "VALLE DE JUAREZ",
      "114": "VILLA CORONA",
      "115": "VILLA GUERRERO",
      "116": "VILLA HIDALGO",
      "117": "CAÑADAS DE OBREGON",
      "118": "YAHUALICA DE GONZALEZ GALLO",
      "119": "ZACOALCO DE TORRES",
      "120": "ZAPOPAN",
      "121": "ZAPOTILTIC",
      "122": "ZAPOTITLAN DE VADILLO",
      "123": "ZAPOTLAN DEL REY",
      "124": "ZAPOTLANEJO",
      "125": "SAN IGNACIO CERRO GORDO"
    },
    "15": {
      "001": "ACAMBAY DE RUIZ CASTAÑEDA",
      "002": "ACOLMAN",
      "003": "ACULCO",
      "004": "ALMOLOYA DE ALQUISIRAS",
      "005": "ALMOLOYA DE JUAREZ",
      "006": "ALMOLOYA DEL RIO",
      "007": "AMANALCO",
      "008": "AMATEPEC",
      "009": "AMECAMECA",
      "010": "APAXCO",
      "011": "ATENCO",
      "012": "ATIZAPAN",
      "013": "ATIZAPAN DE ZARAGOZA",
      "014": "ATLACOMULCO",
      "015": "ATLAUTLA",
      "016": "AXAPUSCO",
      "017": "AYAPANGO",
      "018": "CALIMAYA",
      "019": "CAPULHUAC",
      "020": "COACALCO DE BERRIOZABAL",
      "021": "COATEPEC HARINAS",
      "022": "COCOTITLAN",
      "023": "COYOTEPEC",
      "024": "CUAUTITLAN",
      "025": "CUAUTITLAN IZCALLI",
      "026": "CHALCO",
      "027": "CHAPA DE MOTA",
      "028": "CHAPULTEPEC",
      "029": "CHIAUTLA",
      "030": "CHICOLOAPAN",
      "031": "CHICONCUAC",
      "032": "CHIMALHUACAN",
      "033": "DONATO GUERRA",
      "034": "ECATEPEC DE MORELOS",
      "035": "ECATZINGO",
      "036": "HUEHUETOCA",
      "037": "HUEYPOXTLA",
      "038": "HUIXQUILUCAN",
      "039": "ISIDRO FABELA",
      "040": "IXTAPALUCA",
      "041": "IXTAPAN DE LA SAL",
      "042": "IXTAPAN DEL ORO",
      "043": "IXTLAHUACA",
      "044": "XALATLACO",
      "045": "JALTENCO",
      "046": "JILOTEPEC",
      "047": "JILOTZINGO",
      "048": "JIQUIPILCO",
      "049": "JOCOTITLAN",
      "050": "JOQUICINGO",
      "051": "JUCHITEPEC",
      "052": "LERMA",
      "053": "MALINALCO",
      "054": "MELCHOR OCAMPO",
      "055": "METEPEC",
      "056": "MEXICALTZINGO",
      "057": "MORELOS",
      "058": "NAUCALPAN DE JUAREZ",
      "059": "NEXTLALPAN",
      "060": "NEZAHUALCOYOTL",
      "061": "NICOLAS ROMERO",
      "062": "NOPALTEPEC",
      "063": "OCOYOACAC",
      "064": "OCUILAN",
      "065": "EL ORO",
      "066": "OTUMBA",
      "067": "OTZOLOAPAN",
      "068": "OTZOLOTEPEC",
      "069": "OZUMBA",
      "070": "PAPALOTLA",
      "071": "LA PAZ",
      "072": "POLOTITLAN",
      "073": "RAYON",
      "074": "SAN ANTONIO LA ISLA",
      "075": "SAN FELIPE DEL PROGRESO",
      "076": "SAN MARTIN DE LAS PIRAMIDES",
      "077": "SAN MATEO ATENCO",
      "078": "SAN SIMON DE GUERRERO",
      "079": "SANTO TOMAS",
      "080": "SOYANIQUILPAN DE JUAREZ",
      "081": "SULTEPEC",
      "082": "TECAMAC",
      "083": "TEJUPILCO",
      "084": "TEMAMATLA",
      "085": "TEMASCALAPA",
      "086": "TEMASCALCINGO",
      "087": "TEMASCALTEPEC",
      "088": "TEMOAYA",
      "089": "TENANCINGO",
      "090": "TENANGO DEL AIRE",
      "091": "TENANGO DEL VALLE",
      "092": "TEOLOYUCAN",
      "093": "TEOTIHUACAN",
      "094": "TEPETLAOXTOC",
      "095": "TEPETLIXPA",
      "096": "TEPOTZOTLAN",
      "097": "TEQUIXQUIAC",
      "098": "TEXCALTITLAN",
      "099": "TEXCALYACAC",
      "100": "TEXCOCO",
      "101": "TEZOYUCA",
      "102": "TIANGUISTENCO",
      "103": "TIMILPAN",
      "104": "TLALMANALCO",
      "105": "TLALNEPANTLA DE BAZ",
      "106": "TLATLAYA",
      "107": "TOLUCA",
      "108": "TONATICO",
      "109": "TULTEPEC",
      "110": "TULTITLAN",
      "111": "VALLE DE BRAVO",
      "112": "VILLA DE ALLENDE",
      "113": "VILLA DEL CARBON",
      "114": "VILLA GUERRERO",
      "115": "VILLA VICTORIA",
      "116": "XONACATLAN",
      "117": "ZACAZONAPAN",
      "118": "ZACUALPAN",
      "119": "ZINACANTEPEC",
      "120": "ZUMPAHUACAN",
      "121": "ZUMPANGO",
      "122": "VALLE DE CHALCO SOLIDARIDAD",
      "123": "LUVIANOS",
      "124": "SAN JOSE DEL RINCON",
      "125": "TONANITLA"
    },
    "16": {
      "001": "ACUITZIO",
      "002": "AGUILILLA",
      "003": "ALVARO OBREGON",
      "004": "ANGAMACUTIRO",
      "005": "ANGANGUEO",
      "006": "APATZINGAN",
      "007": "APORO",
      "008": "AQUILA",
      "009": "ARIO",
      "010": "ARTEAGA",
      "011": "BRISEÑAS",
      "012": "BUENAVISTA",
      "013": "CARACUARO",
      "014": "COAHUAYANA",
      "015": "COALCOMAN DE VAZQUEZ PALLARES",
      "016": "COENEO",
      "017": "CONTEPEC",
      "018": "COPANDARO",
      "019": "COTIJA",
      "020": "CUITZEO",
      "021": "CHARAPAN",
      "022": "CHARO",
      "023": "CHAVINDA",
      "024": "CHERAN",
      "025": "CHILCHOTA",
      "026": "CHINICUILA",
      "027": "CHUCANDIRO",
      "028": "CHURINTZIO",
      "029": "CHURUMUCO",
      "030": "ECUANDUREO",
      "031": "EPITACIO HUERTA",
      "032": "ERONGARICUARO",
      "033": "GABRIEL ZAMORA",
      "034": "HIDALGO",
      "035": "LA HUACANA",
      "036": "HUANDACAREO",
      "037": "HUANIQUEO",
      "038": "HUETAMO",
      "039": "HUIRAMBA",
      "040": "INDAPARAPEO",
      "041": "IRIMBO",
      "042": "IXTLAN",
      "043": "JACONA",
      "044": "JIMENEZ",
      "045": "JIQUILPAN",
      "046": "JOSE SIXTO VERDUZCO",
      "047": "JUAREZ",
      "048": "JUNGAPEO",
      "049": "LAGUNILLAS",
      "050": "LAZARO CARDENAS",
      "051": "MADERO",
      "052": "MARAVATIO",
      "053": "MARCOS CASTELLANOS",
      "054": "MORELIA",
      "055": "MORELOS",
      "056": "MUGICA",
      "057": "NAHUATZEN",
      "058": "NOCUPETARO",
      "059": "NUEVO PARANGARICUTIRO",
      "060": "NUEVO URECHO",
      "061": "NUMARAN",
      "062": "OCAMPO",
      "063": "PAJACUARAN",
      "064": "PANINDICUARO",
      "065": "PARACUARO",
      "066": "PARACHO",
      "067": "PATZCUARO",
      "068": "PENJAMILLO",
      "069": "PERIBAN",
      "070": "LA PIEDAD",
      "071": "PUREPERO",
      "072": "PURUANDIRO",
      "073": "QUERENDARO",
      "074": "QUIROGA",
      "075": "COJUMATLAN DE REGULES",
      "076": "LOS REYES",
      "077": "SAHUAYO",
      "078": "SAN LUCAS",
      "079": "SANTA ANA MAYA",
      "080": "SALVADOR ESCALANTE",
      "081": "SENGUIO",
      "082": "SUSUPUATO",
      "083": "TACAMBARO",
      "084": "TANCITARO",
      "085": "TANGAMANDAPIO",
      "086": "TANGANCICUARO",
      "087": "TANHUATO",
      "088": "TARETAN",
      "089": "TARIMBARO",
      "090": "TEPALCATEPEC",
      "091": "TINGAMBATO",
      "092": "TINGÜINDIN",
      "093": "TIQUICHEO DE NICOLAS ROMERO",
      "094": "TLALPUJAHUA",
      "095": "TLAZAZALCA",
      "096": "TOCUMBO",
      "097": "TUMBISCATIO",
      "098": "TURICATO",
      "099": "TUXPAN",
      "100": "TUZANTLA",
      "101": "TZINTZUNTZAN",
      "102": "TZITZIO",
      "103": "URUAPAN",
      "104": "VENUSTIANO CARRANZA",
      "105": "VILLAMAR",
      "106": "VISTA HERMOSA",
      "107": "YURECUARO",
      "108": "ZACAPU",
      "109": "ZAMORA",
      "110": "ZINAPARO",
      "111": "ZINAPECUARO",
      "112": "ZIRACUARETIRO",
      "113": "ZITACUARO"
    },
    "17": {
      "001": "AMACUZAC",
      "002": "ATLATLAHUCAN",
      "003": "AXOCHIAPAN",
      "004": "AYALA",
      "005": "COATLAN DEL RIO",
      "006": "CUAUTLA",
      "007": "CUERNAVACA",
      "008": "EMILIANO ZAPATA",
      "009": "HUITZILAC",
      "010": "JANTETELCO",
      "011": "JIUTEPEC",
      "012": "JOJUTLA",
      "013": "JONACATEPEC",
      "014": "MAZATEPEC",
      "015": "MIACATLAN",
      "016": "OCUITUCO",
      "017": "PUENTE DE IXTLA",
      "018": "TEMIXCO",
      "019": "TEPALCINGO",
      "020": "TEPOZTLAN",
      "021": "TETECALA",
      "022": "TETELA DEL VOLCAN",
      "023": "TLALNEPANTLA",
      "024": "TLALTIZAPAN DE ZAPATA",
      "025": "TLAQUILTENANGO",
      "026": "TLAYACAPAN",
      "027": "TOTOLAPAN",
      "028": "XOCHITEPEC",
      "029": "YAUTEPEC",
      "030": "YECAPIXTLA",
      "031": "ZACATEPEC",
      "032": "ZACUALPAN DE AMILPAS",
      "033": "TEMOAC",
      "034": "COATETELCO",
      "035": "XOXOCOTLA"
    },
    "18": {
      "001": "ACAPONETA",
      "002": "AHUACATLAN",
      "003": "AMATLAN DE CAÑAS",
      "004": "BAHIA DE BANDERAS",
      "005": "COMPOSTELA",
      "006": "HUAJICORI",
      "007": "IXTLAN DEL RIO",
      "008": "JALA",
      "009": "DEL NAYAR",
      "010": "ROSAMORADA",
      "011": "RUIZ",
      "012": "SAN BLAS",
      "013": "SAN PEDRO LAGUNILLAS",
      "014": "SANTA MARIA DEL ORO",
      "015": "SANTIAGO IXCUINTLA",
      "016": "TECUALA",
      "017": "TEPIC",
      "018": "TUXPAN",
      "019": "XALISCO",
      "020": "LA YESCA"
    },
    "19": {
      "001": "ABASOLO",
      "002": "AGUALEGUAS",
      "003": "LOS ALDAMAS",
      "004": "ALLENDE",
      "005": "ANAHUAC",
      "006": "APODACA",
      "007": "ARAMBERRI",
      "008": "BUSTAMANTE",
      "009": "CADEREYTA JIMENEZ",
      "010": "CARMEN",
      "011": "CERRALVO",
      "012": "CIENEGA DE FLORES",
      "013": "CHINA",
      "014": "DR. ARROYO",
      "015": "DR. COSS",
      "016": "DR. GONZALEZ",
      "017": "GALEANA",
      "018": "GARCIA",
      "019": "SAN PEDRO GARZA GARCIA",
      "020": "GRAL. BRAVO",
      "021": "GRAL. ESCOBEDO",
      "022": "GRAL. TERAN",
      "023": "GRAL. TREVIÑO",
      "024": "GRAL. ZARAGOZA",
      "025": "GRAL. ZUAZUA",
      "026": "GUADALUPE",
      "027": "LOS HERRERAS",
      "028": "HIDALGO",
      "029": "HIGUERAS",
      "030": "HUALAHUISES",
      "031": "ITURBIDE",
      "032": "JUAREZ",
      "033": "LAMPAZOS DE NARANJO",
      "034": "LINARES",
      "035": "MARIN",
      "036": "MELCHOR OCAMPO",
      "037": "MIER Y NORIEGA",
      "038": "MINA",
      "039": "MONTEMORELOS",
      "040": "MONTERREY",
      "041": "PARAS",
      "042": "PESQUERIA",
      "043": "LOS RAMONES",
      "044": "RAYONES",
      "045": "SABINAS HIDALGO",
      "046": "SALINAS VICTORIA",
      "047": "SAN NICOLAS DE LOS GARZA",
      "048": "SANTA CATARINA",
      "049": "SANTIAGO",
      "050": "VALLECILLO",
      "051": "VILLALDAMA"
    },
    "20": {
      "001": "ABEJONES",
      "002": "ACATLAN DE PEREZ FIGUEROA",
      "003": "ANIMAS TRUJANO",
      "004": "ASUNCION CACALOTEPEC",
      "005": "ASUNCION CUYOTEPEJI",
      "006": "ASUNCION IXTALTEPEC",
      "007": "ASUNCION NOCHIXTLAN",
      "008": "ASUNCION OCOTLAN",
      "009": "ASUNCION TLACOLULITA",
      "010": "AYOQUEZCO DE ALDAMA",
      "011": "AYOTZINTEPEC",
      "012": "EL BARRIO DE LA SOLEDAD",
      "013": "CALIHUALA",
      "014": "CANDELARIA LOXICHA",
      "015": "CHAHUITES",
      "016": "CHALCATONGO DE HIDALGO",
      "017": "CIENEGA DE ZIMATLAN",
      "018": "COATECAS ALTAS",
      "019": "COICOYAN DE LAS FLORES",
      "020": "LA COMPAÑIA",
      "021": "CONCEPCION BUENAVISTA",
      "022": "CONCEPCION PAPALO",
      "023": "CONSTANCIA DEL ROSARIO",
      "024": "COSOLAPA",
      "025": "COSOLTEPEC",
      "026": "CUILAPAM DE GUERRERO",
      "027": "CUYAMECALCO VILLA DE ZARAGOZA",
      "028": "HEROICA CIUDAD DE EJUTLA DE CRESPO",
      "029": "ELOXOCHITLAN DE FLORES MAGON",
      "030": "EL ESPINAL",
      "031": "FRESNILLO DE TRUJANO",
      "032": "GUADALUPE DE RAMIREZ",
      "033": "GUADALUPE ETLA",
      "034": "GUELATAO DE JUAREZ",
      "035": "GUEVEA DE HUMBOLDT",
      "036": "MESONES HIDALGO",
      "037": "HEROICA CIUDAD DE HUAJUAPAN DE LEON",
      "038": "HUAUTEPEC",
      "039": "HUAUTLA DE JIMENEZ",
      "040": "IXPANTEPEC NIEVES",
      "041": "CIUDAD IXTEPEC",
      "042": "IXTLAN DE JUAREZ",
      "043": "HEROICA CIUDAD DE JUCHITAN DE ZARAGOZA",
      "044": "LOMA BONITA",
      "045": "MAGDALENA APASCO",
      "046": "MAGDALENA JALTEPEC",
      "047": "MAGDALENA MIXTEPEC",
      "048": "MAGDALENA OCOTLAN",
      "049": "MAGDALENA PEÑASCO",
      "050": "MAGDALENA TEITIPAC",
      "051": "MAGDALENA TEQUISISTLAN",
      "052": "MAGDALENA TLACOTEPEC",
      "053": "MAGDALENA YODOCONO DE PORFIRIO DIAZ",
      "054": "MAGDALENA ZAHUATLAN",
      "055": "MARISCALA DE JUAREZ",
      "056": "MARTIRES DE TACUBAYA",
      "057": "MATIAS ROMERO AVENDAÑO",
      "058": "MAZATLAN VILLA DE FLORES",
      "059": "MIAHUATLAN DE PORFIRIO DIAZ",
      "060": "MIXISTLAN DE LA REFORMA",
      "061": "MONJAS",
      "062": "NATIVIDAD",
      "063": "NAZARENO ETLA",
      "064": "NEJAPA DE MADERO",
      "065": "NUEVO ZOQUIAPAM",
      "066": "OAXACA DE JUAREZ",
      "067": "OCOTLAN DE MORELOS",
      "068": "LA PE",
      "069": "PINOTEPA DE DON LUIS",
      "070": "PLUMA HIDALGO",
      "071": "PUTLA VILLA DE GUERRERO",
      "072": "REFORMA DE PINEDA",
      "073": "LA REFORMA",
      "074": "REYES ETLA",
      "075": "ROJAS DE CUAUHTEMOC",
      "076": "SALINA CRUZ",
      "077": "SAN AGUSTIN AMATENGO",
      "078": "SAN AGUSTIN ATENANGO",
      "079": "SAN AGUSTIN CHAYUCO",
      "080": "SAN AGUSTIN DE LAS JUNTAS",
      "081": "SAN AGUSTIN ETLA",
      "082": "SAN AGUSTIN LOXICHA",
      "083": "SAN AGUSTIN TLACOTEPEC",
      "084": "SAN AGUSTIN YATARENI",
      "085": "SAN ANDRES CABECERA NUEVA",
      "086": "SAN ANDRES DINICUITI",
      "087": "SAN ANDRES HUAXPALTEPEC",
      "088": "SAN ANDRES HUAYAPAM",
      "089": "SAN ANDRES IXTLAHUACA",
      "090": "SAN ANDRES LAGUNAS",
      "091": "SAN ANDRES NUXIÑO",
      "092": "SAN ANDRES PAXTLAN",
      "093": "SAN ANDRES SINAXTLA",
      "094": "SAN ANDRES SOLAGA",
      "095": "SAN ANDRES TEOTILALPAM",
      "096": "SAN ANDRES TEPETLAPA",
      "097": "SAN ANDRES YAA",
      "098": "SAN ANDRES ZABACHE",
      "099": "SAN ANDRES ZAUTLA",
      "100": "SAN ANTONINO CASTILLO VELASCO",
      "101": "SAN ANTONINO EL ALTO",
      "102": "SAN ANTONINO MONTE VERDE",
      "103": "SAN ANTONIO ACUTLA",
      "104": "SAN ANTONIO DE LA CAL",
      "105": "SAN ANTONIO HUITEPEC",
      "106": "SAN ANTONIO NANAHUATIPAM",
      "107": "SAN ANTONIO SINICAHUA",
      "108": "SAN ANTONIO TEPETLAPA",
      "109": "SAN BALTAZAR CHICHICAPAM",
      "110": "SAN BALTAZAR LOXICHA",
      "111": "SAN BALTAZAR YATZACHI EL BAJO",
      "112": "SAN BARTOLO COYOTEPEC",
      "113": "SAN BARTOLO SOYALTEPEC",
      "114": "SAN BARTOLO YAUTEPEC",
      "115": "SAN BARTOLOME AYAUTLA",
      "116": "SAN BARTOLOME LOXICHA",
      "117": "SAN BARTOLOME QUIALANA",
      "118": "SAN BARTOLOME YUCUAÑE",
      "119": "SAN BARTOLOME ZOOGOCHO",
      "120": "SAN BERNARDO MIXTEPEC",
      "121": "SAN BLAS ATEMPA",
      "122": "SAN CARLOS YAUTEPEC",
      "123": "SAN CRISTOBAL AMATLAN",
      "124": "SAN CRISTOBAL AMOLTEPEC",
      "125": "SAN CRISTOBAL LACHIRIOAG",
      "126": "SAN CRISTOBAL SUCHIXTLAHUACA",
      "127": "SAN DIONISIO DEL MAR",
      "128": "SAN DIONISIO OCOTEPEC",
      "129": "SAN DIONISIO OCOTLAN",
      "130": "SAN ESTEBAN ATATLAHUCA",
      "131": "SAN FELIPE JALAPA DE DIAZ",
      "132": "SAN FELIPE TEJALAPAM",
      "133": "SAN FELIPE USILA",
      "134": "SAN FRANCISCO CAHUACUA",
      "135": "SAN FRANCISCO CAJONOS",
      "136": "SAN FRANCISCO CHAPULAPA",
      "137": "SAN FRANCISCO CHINDUA",
      "138": "SAN FRANCISCO DEL MAR",
      "139": "SAN FRANCISCO HUEHUETLAN",
      "140": "SAN FRANCISCO IXHUATAN",
      "141": "SAN FRANCISCO JALTEPETONGO",
      "142": "SAN FRANCISCO LACHIGOLO",
      "143": "SAN FRANCISCO LOGUECHE",
      "144": "SAN FRANCISCO NUXAÑO",
      "145": "SAN FRANCISCO OZOLOTEPEC",
      "146": "SAN FRANCISCO SOLA",
      "147": "SAN FRANCISCO TELIXTLAHUACA",
      "148": "SAN FRANCISCO TEOPAN",
      "149": "SAN FRANCISCO TLAPANCINGO",
      "150": "SAN GABRIEL MIXTEPEC",
      "151": "SAN ILDEFONSO AMATLAN",
      "152": "SAN ILDEFONSO SOLA",
      "153": "SAN ILDEFONSO VILLA ALTA",
      "154": "SAN JACINTO AMILPAS",
      "155": "SAN JACINTO TLACOTEPEC",
      "156": "SAN JERONIMO COATLAN",
      "157": "SAN JERONIMO SILACAYOAPILLA",
      "158": "SAN JERONIMO SOSOLA",
      "159": "SAN JERONIMO TAVICHE",
      "160": "SAN JERONIMO TECOATL",
      "161": "SAN JERONIMO TLACOCHAHUAYA",
      "162": "SAN JORGE NUCHITA",
      "163": "SAN JOSE AYUQUILA",
      "164": "SAN JOSE CHILTEPEC",
      "165": "SAN JOSE DEL PEÑASCO",
      "166": "SAN JOSE ESTANCIA GRANDE",
      "167": "SAN JOSE INDEPENDENCIA",
      "168": "SAN JOSE LACHIGUIRI",
      "169": "SAN JOSE DEL PROGRESO",
      "170": "SAN JOSE TENANGO",
      "171": "SAN JUAN ACHIUTLA",
      "172": "SAN JUAN ATEPEC",
      "173": "SAN JUAN BAUTISTA ATATLAHUCA",
      "174": "SAN JUAN BAUTISTA COIXTLAHUACA",
      "175": "SAN JUAN BAUTISTA CUICATLAN",
      "176": "SAN JUAN BAUTISTA GUELACHE",
      "177": "SAN JUAN BAUTISTA JAYACATLAN",
      "178": "SAN JUAN BAUTISTA LO DE SOTO",
      "179": "SAN JUAN BAUTISTA SUCHITEPEC",
      "180": "SAN JUAN BAUTISTA TLACHICHILCO",
      "181": "SAN JUAN BAUTISTA TLACOATZINTEPEC",
      "182": "SAN JUAN BAUTISTA TUXTEPEC",
      "183": "SAN JUAN BAUTISTA VALLE NACIONAL",
      "184": "SAN JUAN CACAHUATEPEC",
      "185": "SAN JUAN CHICOMEZUCHIL",
      "186": "SAN JUAN CHILATECA",
      "187": "CHIQUIHUITLAN DE BENITO JUAREZ",
      "188": "SAN JUAN CIENEGUILLA",
      "189": "SAN JUAN COATZOSPAM",
      "190": "SAN JUAN COLORADO",
      "191": "SAN JUAN COMALTEPEC",
      "192": "SAN JUAN COTZOCON",
      "193": "SAN JUAN DE LOS CUES",
      "194": "SAN JUAN DEL ESTADO",
      "195": "SAN JUAN DEL RIO",
      "196": "SAN JUAN DIUXI",
      "197": "SAN JUAN EVANGELISTA ANALCO",
      "198": "SAN JUAN GUELAVIA",
      "199": "SAN JUAN GUICHICOVI",
      "200": "SAN JUAN IHUALTEPEC",
      "201": "SAN JUAN JUQUILA MIXES",
      "202": "SAN JUAN JUQUILA VIJANOS",
      "203": "SAN JUAN LACHAO",
      "204": "SAN JUAN LACHIGALLA",
      "205": "SAN JUAN LAJARCIA",
      "206": "SAN JUAN LALANA",
      "207": "SAN JUAN MAZATLAN",
      "208": "SAN JUAN MIXTEPEC",
      "209": "SAN JUAN MIXTEPEC",
      "210": "SAN JUAN ÑUMI",
      "211": "SAN JUAN OZOLOTEPEC",
      "212": "SAN JUAN PETLAPA",
      "213": "SAN JUAN QUIAHIJE",
      "214": "SAN JUAN QUIOTEPEC",
      "215": "SAN JUAN SAYULTEPEC",
      "216": "SAN JUAN TABAA",
      "217": "SAN JUAN TAMAZOLA",
      "218": "SAN JUAN TEITA",
      "219": "SAN JUAN TEITIPAC",
      "220": "SAN JUAN TEPEUXILA",
      "221": "SAN JUAN TEPOSCOLULA",
      "222": "SAN JUAN YAEE",
      "223": "SAN JUAN YATZONA",
      "224": "SAN JUAN YUCUITA",
      "225": "SAN LORENZO",
      "226": "SAN LORENZO ALBARRADAS",
      "227": "SAN LORENZO CACAOTEPEC",
      "228": "SAN LORENZO CUAUNECUILTITLA",
      "229": "SAN LORENZO TEXMELUCAN",
      "230": "SAN LORENZO VICTORIA",
      "231": "SAN LUCAS CAMOTLAN",
      "232": "SAN LUCAS OJITLAN",
      "233": "SAN LUCAS QUIAVINI",
      "234": "SAN LUCAS ZOQUIAPAM",
      "235": "SAN LUIS AMATLAN",
      "236": "SAN MARCIAL OZOLOTEPEC",
      "237": "SAN MARCOS ARTEAGA",
      "238": "SAN MARTIN DE LOS CANSECOS",
      "239": "SAN MARTIN HUAMELULPAM",
      "240": "SAN MARTIN ITUNYOSO",
      "241": "SAN MARTIN LACHILA",
      "242": "SAN MARTIN PERAS",
      "243": "SAN MARTIN TILCAJETE",
      "244": "SAN MARTIN TOXPALAN",
      "245": "SAN MARTIN ZACATEPEC",
      "246": "SAN MATEO CAJONOS",
      "247": "SAN MATEO DEL MAR",
      "248": "SAN MATEO ETLATONGO",
      "249": "SAN MATEO NEJAPAM",
      "250": "SAN MATEO PEÑASCO",
      "251": "SAN MATEO PIÑAS",
      "252": "SAN MATEO RIO HONDO",
      "253": "SAN MATEO SINDIHUI",
      "254": "SAN MATEO TLAPILTEPEC",
      "255": "SAN MATEO YOLOXOCHITLAN",
      "256": "SAN MELCHOR BETAZA",
      "257": "SAN MIGUEL ACHIUTLA",
      "258": "SAN MIGUEL AHUEHUETITLAN",
      "259": "SAN MIGUEL ALOAPAM",
      "260": "SAN MIGUEL AMATITLAN",
      "261": "SAN MIGUEL AMATLAN",
      "262": "SAN MIGUEL CHICAHUA",
      "263": "SAN MIGUEL CHIMALAPA",
      "264": "SAN MIGUEL COATLAN",
      "265": "SAN MIGUEL DEL PUERTO",
      "266": "SAN MIGUEL DEL RIO",
      "267": "SAN MIGUEL EJUTLA",
      "268": "SAN MIGUEL EL GRANDE",
      "269": "SAN MIGUEL HUAUTLA",
      "270": "SAN MIGUEL MIXTEPEC",
      "271": "SAN MIGUEL PANIXTLAHUACA",
      "272": "SAN MIGUEL PERAS",
      "273": "SAN MIGUEL PIEDRAS",
      "274": "SAN MIGUEL QUETZALTEPEC",
      "275": "SAN MIGUEL SANTA FLOR",
      "276": "SAN MIGUEL SOYALTEPEC",
      "277": "SAN MIGUEL SUCHIXTEPEC",
      "278": "VILLA TALEA DE CASTRO",
      "279": "SAN MIGUEL TECOMATLAN",
      "280": "SAN MIGUEL TENANGO",
      "281": "SAN MIGUEL TEQUIXTEPEC",
      "282": "SAN MIGUEL TILQUIAPAM",
      "283": "SAN MIGUEL TLACAMAMA",
      "284": "SAN MIGUEL TLACOTEPEC",
      "285": "SAN MIGUEL TULANCINGO",
      "286": "SAN MIGUEL YOTAO",
      "287": "SAN NICOLAS",
      "288": "SAN NICOLAS HIDALGO",
      "289": "SAN PABLO COATLAN",
      "290": "SAN PABLO CUATRO VENADOS",
      "291": "SAN PABLO ETLA",
      "292": "SAN PABLO HUITZO",
      "293": "SAN PABLO HUIXTEPEC",
      "294": "SAN PABLO MACUILTIANGUIS",
      "295": "SAN PABLO TIJALTEPEC",
      "296": "SAN PABLO VILLA DE MITLA",
      "297": "SAN PABLO YAGANIZA",
      "298": "SAN PEDRO AMUZGOS",
      "299": "SAN PEDRO APOSTOL",
      "300": "SAN PEDRO ATOYAC",
      "301": "SAN PEDRO CAJONOS",
      "302": "SAN PEDRO COXCALTEPEC CANTAROS",
      "303": "SAN PEDRO COMITANCILLO",
      "304": "SAN PEDRO EL ALTO",
      "305": "SAN PEDRO HUAMELULA",
      "306": "SAN PEDRO HUILOTEPEC",
      "307": "SAN PEDRO IXCATLAN",
      "308": "SAN PEDRO IXTLAHUACA",
      "309": "SAN PEDRO JALTEPETONGO",
      "310": "SAN PEDRO JICAYAN",
      "311": "SAN PEDRO JOCOTIPAC",
      "312": "SAN PEDRO JUCHATENGO",
      "313": "SAN PEDRO MARTIR",
      "314": "SAN PEDRO MARTIR QUIECHAPA",
      "315": "SAN PEDRO MARTIR YUCUXACO",
      "316": "SAN PEDRO MIXTEPEC",
      "317": "SAN PEDRO MIXTEPEC",
      "318": "SAN PEDRO MOLINOS",
      "319": "SAN PEDRO NOPALA",
      "320": "SAN PEDRO OCOPETATILLO",
      "321": "SAN PEDRO OCOTEPEC",
      "322": "SAN PEDRO POCHUTLA",
      "323": "SAN PEDRO QUIATONI",
      "324": "SAN PEDRO SOCHIAPAM",
      "325": "SAN PEDRO TAPANATEPEC",
      "326": "SAN PEDRO TAVICHE",
      "327": "SAN PEDRO TEOZACOALCO",
      "328": "SAN PEDRO TEUTILA",
      "329": "SAN PEDRO TIDAA",
      "330": "SAN PEDRO TOPILTEPEC",
      "331": "SAN PEDRO TOTOLAPAM",
      "332": "VILLA DE TUTUTEPEC",
      "333": "SAN PEDRO Y SAN PABLO AYUTLA",
      "334": "SAN PEDRO Y SAN PABLO TEPOSCOLULA",
      "335": "SAN PEDRO Y SAN PABLO TEQUIXTEPEC",
      "336": "SAN PEDRO YANERI",
      "337": "SAN PEDRO YOLOX",
      "338": "SAN PEDRO YUCUNAMA",
      "339": "SAN RAYMUNDO JALPAN",
      "340": "SAN SEBASTIAN ABASOLO",
      "341": "SAN SEBASTIAN COATLAN",
      "342": "SAN SEBASTIAN IXCAPA",
      "343": "SAN SEBASTIAN NICANANDUTA",
      "344": "SAN SEBASTIAN RIO HONDO",
      "345": "SAN SEBASTIAN TECOMAXTLAHUACA",
      "346": "SAN SEBASTIAN TEITIPAC",
      "347": "SAN SEBASTIAN TUTLA",
      "348": "SAN SIMON ALMOLONGAS",
      "349": "SAN SIMON ZAHUATLAN",
      "350": "SAN VICENTE COATLAN",
      "351": "SAN VICENTE LACHIXIO",
      "352": "SAN VICENTE NUÑU",
      "353": "SANTA ANA",
      "354": "SANTA ANA ATEIXTLAHUACA",
      "355": "SANTA ANA CUAUHTEMOC",
      "356": "SANTA ANA DEL VALLE",
      "357": "SANTA ANA TAVELA",
      "358": "SANTA ANA TLAPACOYAN",
      "359": "SANTA ANA YARENI",
      "360": "SANTA ANA ZEGACHE",
      "361": "SANTA CATALINA QUIERI",
      "362": "SANTA CATARINA CUIXTLA",
      "363": "SANTA CATARINA IXTEPEJI",
      "364": "SANTA CATARINA JUQUILA",
      "365": "SANTA CATARINA LACHATAO",
      "366": "SANTA CATARINA LOXICHA",
      "367": "SANTA CATARINA MECHOACAN",
      "368": "SANTA CATARINA MINAS",
      "369": "SANTA CATARINA QUIANE",
      "370": "SANTA CATARINA QUIOQUITANI",
      "371": "SANTA CATARINA TAYATA",
      "372": "SANTA CATARINA TICUA",
      "373": "SANTA CATARINA YOSONOTU",
      "374": "SANTA CATARINA ZAPOQUILA",
      "375": "SANTA CRUZ ACATEPEC",
      "376": "SANTA CRUZ AMILPAS",
      "377": "SANTA CRUZ DE BRAVO",
      "378": "SANTA CRUZ ITUNDUJIA",
      "379": "SANTA CRUZ MIXTEPEC",
      "380": "SANTA CRUZ NUNDACO",
      "381": "SANTA CRUZ PAPALUTLA",
      "382": "SANTA CRUZ TACACHE DE MINA",
      "383": "SANTA CRUZ TACAHUA",
      "384": "SANTA CRUZ TAYATA",
      "385": "SANTA CRUZ XITLA",
      "386": "SANTA CRUZ XOXOCOTLAN",
      "387": "SANTA CRUZ ZENZONTEPEC",
      "388": "SANTA GERTRUDIS",
      "389": "SANTA INES DEL MONTE",
      "390": "SANTA INES YATZECHE",
      "391": "SANTA INES DE ZARAGOZA",
      "392": "SANTA LUCIA DEL CAMINO",
      "393": "SANTA LUCIA MIAHUATLAN",
      "394": "SANTA LUCIA MONTEVERDE",
      "395": "SANTA LUCIA OCOTLAN",
      "396": "SANTA MAGDALENA JICOTLAN",
      "397": "SANTA MARIA ALOTEPEC",
      "398": "SANTA MARIA APAZCO",
      "399": "SANTA MARIA LA ASUNCION",
      "400": "SANTA MARIA ATZOMPA",
      "401": "SANTA MARIA CAMOTLAN",
      "402": "SANTA MARIA CHACHOAPAM",
      "403": "VILLA DE CHILAPA DE DIAZ",
      "404": "SANTA MARIA CHILCHOTLA",
      "405": "SANTA MARIA CHIMALAPA",
      "406": "SANTA MARIA COLOTEPEC",
      "407": "SANTA MARIA CORTIJO",
      "408": "SANTA MARIA COYOTEPEC",
      "409": "SANTA MARIA DEL ROSARIO",
      "410": "SANTA MARIA DEL TULE",
      "411": "SANTA MARIA ECATEPEC",
      "412": "SANTA MARIA GUELACE",
      "413": "SANTA MARIA GUIENAGATI",
      "414": "SANTA MARIA HUATULCO",
      "415": "SANTA MARIA HUAZOLOTITLAN",
      "416": "SANTA MARIA IPALAPA",
      "417": "SANTA MARIA IXCATLAN",
      "418": "SANTA MARIA JACATEPEC",
      "419": "SANTA MARIA JALAPA DEL MARQUES",
      "420": "SANTA MARIA JALTIANGUIS",
      "421": "SANTA MARIA LACHIXIO",
      "422": "SANTA MARIA MIXTEQUILLA",
      "423": "SANTA MARIA NATIVITAS",
      "424": "SANTA MARIA NDUAYACO",
      "425": "SANTA MARIA OZOLOTEPEC",
      "426": "SANTA MARIA PAPALO",
      "427": "SANTA MARIA PETAPA",
      "428": "SANTA MARIA PEÑOLES",
      "429": "SANTA MARIA QUIEGOLANI",
      "430": "SANTA MARIA SOLA",
      "431": "SANTA MARIA TATALTEPEC",
      "432": "SANTA MARIA TECOMAVACA",
      "433": "SANTA MARIA TEMAXCALAPA",
      "434": "SANTA MARIA TEMAXCALTEPEC",
      "435": "SANTA MARIA TEOPOXCO",
      "436": "SANTA MARIA TEPANTLALI",
      "437": "SANTA MARIA TEXCATITLAN",
      "438": "SANTA MARIA TLAHUITOLTEPEC",
      "439": "SANTA MARIA TLALIXTAC",
      "440": "SANTA MARIA TONAMECA",
      "441": "SANTA MARIA TOTOLAPILLA",
      "442": "SANTA MARIA XADANI",
      "443": "SANTA MARIA YALINA",
      "444": "SANTA MARIA YAVESIA",
      "445": "SANTA MARIA YOLOTEPEC",
      "446": "SANTA MARIA YOSOYUA",
      "447": "SANTA MARIA YUCUHITI",
      "448": "SANTA MARIA ZACATEPEC",
      "449": "SANTA MARIA ZANIZA",
      "450": "SANTA MARIA ZOQUITLAN",
      "451": "SANTIAGO AMOLTEPEC",
      "452": "SANTIAGO APOALA",
      "453": "SANTIAGO APOSTOL",
      "454": "SANTIAGO ASTATA",
      "455": "SANTIAGO ATITLAN",
      "456": "SANTIAGO AYUQUILILLA",
      "457": "SANTIAGO CACALOXTEPEC",
      "458": "SANTIAGO CAMOTLAN",
      "459": "SANTIAGO CHAZUMBA",
      "460": "SANTIAGO CHOAPAM",
      "461": "SANTIAGO COMALTEPEC",
      "462": "SANTIAGO DEL RIO",
      "463": "SANTIAGO HUAJOLOTITLAN",
      "464": "SANTIAGO HUAUCLILLA",
      "465": "SANTIAGO IHUITLAN PLUMAS",
      "466": "SANTIAGO IXCUINTEPEC",
      "467": "SANTIAGO IXTAYUTLA",
      "468": "SANTIAGO JAMILTEPEC",
      "469": "SANTIAGO JOCOTEPEC",
      "470": "SANTIAGO JUXTLAHUACA",
      "471": "SANTIAGO LACHIGUIRI",
      "472": "SANTIAGO LALOPA",
      "473": "SANTIAGO LAOLLAGA",
      "474": "SANTIAGO LAXOPA",
      "475": "SANTIAGO LLANO GRANDE",
      "476": "SANTIAGO MATATLAN",
      "477": "SANTIAGO MILTEPEC",
      "478": "SANTIAGO MINAS",
      "479": "SANTIAGO NACALTEPEC",
      "480": "SANTIAGO NEJAPILLA",
      "481": "SANTIAGO NILTEPEC",
      "482": "SANTIAGO NUNDICHE",
      "483": "SANTIAGO NUYOO",
      "484": "SANTIAGO PINOTEPA NACIONAL",
      "485": "SANTIAGO SUCHILQUITONGO",
      "486": "SANTIAGO TAMAZOLA",
      "487": "SANTIAGO TAPEXTLA",
      "488": "SANTIAGO TENANGO",
      "489": "SANTIAGO TEPETLAPA",
      "490": "SANTIAGO TETEPEC",
      "491": "SANTIAGO TEXCALCINGO",
      "492": "SANTIAGO TEXTITLAN",
      "493": "SANTIAGO TILANTONGO",
      "494": "SANTIAGO TILLO",
      "495": "SANTIAGO TLAZOYALTEPEC",
      "496": "SANTIAGO XANICA",
      "497": "SANTIAGO XIACUI",
      "498": "SANTIAGO YAITEPEC",
      "499": "SANTIAGO YAVEO",
      "500": "SANTIAGO YOLOMECATL",
      "501": "SANTIAGO YOSONDUA",
      "502": "SANTIAGO YUCUYACHI",
      "503": "SANTIAGO ZACATEPEC",
      "504": "SANTIAGO ZOOCHILA",
      "505": "SANTO DOMINGO ALBARRADAS",
      "506": "SANTO DOMINGO ARMENTA",
      "507": "SANTO DOMINGO CHIHUITAN",
      "508": "SANTO DOMINGO DE MORELOS",
      "509": "SANTO DOMINGO INGENIO",
      "510": "SANTO DOMINGO IXCATLAN",
      "511": "SANTO DOMINGO NUXAA",
      "512": "SANTO DOMINGO OZOLOTEPEC",
      "513": "SANTO DOMINGO PETAPA",
      "514": "SANTO DOMINGO ROAYAGA",
      "515": "SANTO DOMINGO TEHUANTEPEC",
      "516": "SANTO DOMINGO TEOJOMULCO",
      "517": "SANTO DOMINGO TEPUXTEPEC",
      "518": "SANTO DOMINGO TLATAYAPAM",
      "519": "SANTO DOMINGO TOMALTEPEC",
      "520": "SANTO DOMINGO TONALA",
      "521": "SANTO DOMINGO TONALTEPEC",
      "522": "SANTO DOMINGO XAGACIA",
      "523": "SANTO DOMINGO YANHUITLAN",
      "524": "SANTO DOMINGO YODOHINO",
      "525": "SANTO DOMINGO ZANATEPEC",
      "526": "SANTO TOMAS JALIEZA",
      "527": "SANTO TOMAS MAZALTEPEC",
      "528": "SANTO TOMAS OCOTEPEC",
      "529": "SANTO TOMAS TAMAZULAPAN",
      "530": "SANTOS REYES NOPALA",
      "531": "SANTOS REYES PAPALO",
      "532": "SANTOS REYES TEPEJILLO",
      "533": "SANTOS REYES YUCUNA",
      "534": "SILACAYOAPAM",
      "535": "SITIO DE XITLAPEHUA",
      "536": "VILLA SOLA DE VEGA",
      "537": "SOLEDAD ETLA",
      "538": "TANICHE",
      "539": "VILLA DE TAMAZULAPAM DEL PROGRESO",
      "540": "TAMAZULAPAM DEL ESPIRITU SANTO",
      "541": "TANETZE DE ZARAGOZA",
      "542": "TATALTEPEC DE VALDES",
      "543": "VILLA TEJUPAM DE LA UNION",
      "544": "TEOCOCUILCO DE MARCOS PEREZ",
      "545": "TEOTITLAN DE FLORES MAGON",
      "546": "TEOTITLAN DEL VALLE",
      "547": "TEOTONGO",
      "548": "TEPELMEME VILLA DE MORELOS",
      "549": "H VILLA TEZOATLAN SEGURA Y LUNA CUNA IND OAX",
      "550": "TLACOLULA DE MATAMOROS",
      "551": "TLACOTEPEC PLUMAS",
      "552": "TLALIXTAC DE CABRERA",
      "553": "HEROICA CIUDAD DE TLAXIACO",
      "554": "TOTONTEPEC VILLA DE MORELOS",
      "555": "TRINIDAD ZAACHILA",
      "556": "LA TRINIDAD VISTA HERMOSA",
      "557": "UNION HIDALGO",
      "558": "VALERIO TRUJANO",
      "559": "CAPULALPAM DE MENDEZ",
      "560": "VILLA DE ETLA",
      "561": "VILLA DIAZ ORDAZ",
      "562": "VILLA HIDALGO",
      "563": "YAXE",
      "564": "YOGANA",
      "565": "YUTANDUCHI DE GUERRERO",
      "566": "VILLA DE ZAACHILA",
      "567": "SAN MATEO YUCUTINDOO",
      "568": "ZAPOTITLAN LAGUNAS",
      "569": "ZAPOTITLAN PALMAS",
      "570": "ZIMATLAN DE ALVAREZ"
    },
    "21": {
      "001": "ACAJETE",
      "002": "ACATENO",
      "003": "ACATLAN",
      "004": "ACATZINGO",
      "005": "ACTEOPAN",
      "006": "AHUACATLAN",
      "007": "AHUATLAN",
      "008": "AHUAZOTEPEC",
      "009": "AHUEHUETITLA",
      "010": "AJALPAN",
      "011": "ALBINO ZERTUCHE",
      "012": "ALJOJUCA",
      "013": "ALTEPEXI",
      "014": "AMIXTLAN",
      "015": "AMOZOC",
      "016": "AQUIXTLA",
      "017": "ATEMPAN",
      "018": "ATEXCAL",
      "019": "ATLIXCO",
      "020": "ATOYATEMPAN",
      "021": "ATZALA",
      "022": "ATZITZIHUACAN",
      "023": "ATZITZINTLA",
      "024": "AXUTLA",
      "025": "AYOTOXCO DE GUERRERO",
      "026": "CALPAN",
      "027": "CALTEPEC",
      "028": "CAMOCUAUTLA",
      "029": "CAÑADA MORELOS",
      "030": "CAXHUACAN",
      "031": "COATEPEC",
      "032": "COATZINGO",
      "033": "COHETZALA",
      "034": "COHUECAN",
      "035": "CORONANGO",
      "036": "COXCATLAN",
      "037": "COYOMEAPAN",
      "038": "COYOTEPEC",
      "039": "CUAPIAXTLA DE MADERO",
      "040": "CUAUTEMPAN",
      "041": "CUAUTINCHAN",
      "042": "CUAUTLANCINGO",
      "043": "CUAYUCA DE ANDRADE",
      "044": "CUETZALAN DEL PROGRESO",
      "045": "CUYOACO",
      "046": "CHALCHICOMULA DE SESMA",
      "047": "CHAPULCO",
      "048": "CHIAUTLA",
      "049": "CHIAUTZINGO",
      "050": "CHICONCUAUTLA",
      "051": "CHICHIQUILA",
      "052": "CHIETLA",
      "053": "CHIGMECATITLAN",
      "054": "CHIGNAHUAPAN",
      "055": "CHIGNAUTLA",
      "056": "CHILA",
      "057": "CHILA DE LA SAL",
      "058": "HONEY",
      "059": "CHILCHOTLA",
      "060": "CHINANTLA",
      "061": "DOMINGO ARENAS",
      "062": "ELOXOCHITLAN",
      "063": "EPATLAN",
      "064": "ESPERANZA",
      "065": "FRANCISCO Z. MENA",
      "066": "GENERAL FELIPE ANGELES",
      "067": "GUADALUPE",
      "068": "GUADALUPE VICTORIA",
      "069": "HERMENEGILDO GALEANA",
      "070": "HUAQUECHULA",
      "071": "HUATLATLAUCA",
      "072": "HUAUCHINANGO",
      "073": "HUEHUETLA",
      "074": "HUEHUETLAN EL CHICO",
      "075": "HUEHUETLAN EL GRANDE",
      "076": "HUEJOTZINGO",
      "077": "HUEYAPAN",
      "078": "HUEYTAMALCO",
      "079": "HUEYTLALPAN",
      "080": "HUITZILAN DE SERDAN",
      "081": "HUITZILTEPEC",
      "082": "ATLEQUIZAYAN",
      "083": "IXCAMILPA DE GUERRERO",
      "084": "IXCAQUIXTLA",
      "085": "IXTACAMAXTITLAN",
      "086": "IXTEPEC",
      "087": "IZUCAR DE MATAMOROS",
      "088": "JALPAN",
      "089": "JOLALPAN",
      "090": "JONOTLA",
      "091": "JOPALA",
      "092": "JUAN C. BONILLA",
      "093": "JUAN GALINDO",
      "094": "JUAN N. MENDEZ",
      "095": "LAFRAGUA",
      "096": "LIBRES",
      "097": "LA MAGDALENA TLATLAUQUITEPEC",
      "098": "MAZAPILTEPEC DE JUAREZ",
      "099": "MIXTLA",
      "100": "MOLCAXAC",
      "101": "NAUPAN",
      "102": "NAUZONTLA",
      "103": "NEALTICAN",
      "104": "NICOLAS BRAVO",
      "105": "NOPALUCAN",
      "106": "OCOTEPEC",
      "107": "OCOYUCAN",
      "108": "OLINTLA",
      "109": "ORIENTAL",
      "110": "PAHUATLAN",
      "111": "PALMAR DE BRAVO",
      "112": "PANTEPEC",
      "113": "PETLALCINGO",
      "114": "PIAXTLA",
      "115": "PUEBLA",
      "116": "QUECHOLAC",
      "117": "QUIMIXTLAN",
      "118": "RAFAEL LARA GRAJALES",
      "119": "LOS REYES DE JUAREZ",
      "120": "SAN ANDRES CHOLULA",
      "121": "SAN ANTONIO CAÑADA",
      "122": "SAN DIEGO LA MESA TOCHIMILTZINGO",
      "123": "SAN FELIPE TEOTLALCINGO",
      "124": "SAN FELIPE TEPATLAN",
      "125": "SAN GABRIEL CHILAC",
      "126": "SAN GREGORIO ATZOMPA",
      "127": "SAN JERONIMO TECUANIPAN",
      "128": "SAN JERONIMO XAYACATLAN",
      "129": "SAN JOSE CHIAPA",
      "130": "SAN JOSE MIAHUATLAN",
      "131": "SAN JUAN ATENCO",
      "132": "SAN JUAN ATZOMPA",
      "133": "SAN MARTIN TEXMELUCAN",
      "134": "SAN MARTIN TOTOLTEPEC",
      "135": "SAN MATIAS TLALANCALECA",
      "136": "SAN MIGUEL IXITLAN",
      "137": "SAN MIGUEL XOXTLA",
      "138": "SAN NICOLAS BUENOS AIRES",
      "139": "SAN NICOLAS DE LOS RANCHOS",
      "140": "SAN PABLO ANICANO",
      "141": "SAN PEDRO CHOLULA",
      "142": "SAN PEDRO YELOIXTLAHUACA",
      "143": "SAN SALVADOR EL SECO",
      "144": "SAN SALVADOR EL VERDE",
      "145": "SAN SALVADOR HUIXCOLOTLA",
      "146": "SANTA CATARINA TLALTEMPAN",
      "147": "SANTA INES AHUATEMPAN",
      "148": "SANTA ISABEL CHOLULA",
      "149": "SANTIAGO MIAHUATLAN",
      "150": "SANTO TOMAS HUEYOTLIPAN",
      "151": "SOLTEPEC",
      "152": "TECALI DE HERRERA",
      "153": "TECAMACHALCO",
      "154": "TECOMATLAN",
      "155": "TEHUACAN",
      "156": "TEHUITZINGO",
      "157": "TENAMPULCO",
      "158": "TEOPANTLAN",
      "159": "TEOTLALCO",
      "160": "TEPANCO DE LOPEZ",
      "161": "TEPANGO DE RODRIGUEZ",
      "162": "TEPATLAXCO DE HIDALGO",
      "163": "TEPEACA",
      "164": "TEPEMAXALCO",
      "165": "TEPEOJUMA",
      "166": "TEPETZINTLA",
      "167": "TEPEXCO",
      "168": "TEPEXI DE RODRIGUEZ",
      "169": "TEPEYAHUALCO",
      "170": "TEPEYAHUALCO DE CUAUHTEMOC",
      "171": "TETELA DE OCAMPO",
      "172": "TETELES DE AVILA CASTILLO",
      "173": "TEZIUTLAN",
      "174": "TIANGUISMANALCO",
      "175": "TILAPA",
      "176": "TLACOTEPEC DE BENITO JUAREZ",
      "177": "SAN SEBASTIAN TLACOTEPEC",
      "178": "TLACUILOTEPEC",
      "179": "TLACHICHUCA",
      "180": "TLAHUAPAN",
      "181": "TLALTENANGO",
      "182": "TLANEPANTLA",
      "183": "TLAOLA",
      "184": "TLAPACOYA",
      "185": "TLAPANALA",
      "186": "TLATLAUQUITEPEC",
      "187": "TLAXCO",
      "188": "TOCHIMILCO",
      "189": "TOCHTEPEC",
      "190": "TOTOLTEPEC DE GUERRERO",
      "191": "TULCINGO",
      "192": "TUZAMAPAN DE GALEANA",
      "193": "TZICATLACOYAN",
      "194": "VENUSTIANO CARRANZA",
      "195": "VICENTE GUERRERO",
      "196": "XAYACATLAN DE BRAVO",
      "197": "XICOTEPEC",
      "198": "XICOTLAN",
      "199": "XIUTETELCO",
      "200": "XOCHIAPULCO",
      "201": "XOCHILTEPEC",
      "202": "XOCHITLAN DE VICENTE SUAREZ",
      "203": "XOCHITLAN TODOS SANTOS",
      "204": "YAONAHUAC",
      "205": "YEHUALTEPEC",
      "206": "ZACAPALA",
      "207": "ZACAPOAXTLA",
      "208": "ZACATLAN",
      "209": "ZAPOTITLAN",
      "210": "ZAPOTITLAN DE MENDEZ",
      "211": "ZARAGOZA",
      "212": "ZAUTLA",
      "213": "ZIHUATEUTLA",
      "214": "ZINACATEPEC",
      "215": "ZONGOZOTLA",
      "216": "ZOQUIAPAN",
      "217": "ZOQUITLAN"
    },
    "22": {
      "001": "AMEALCO DE BONFIL",
      "002": "ARROYO SECO",
      "003": "CADEREYTA DE MONTES",
      "004": "COLON",
      "005": "CORREGIDORA",
      "006": "EZEQUIEL MONTES",
      "007": "HUIMILPAN",
      "008": "JALPAN DE SERRA",
      "009": "LANDA DE MATAMOROS",
      "010": "EL MARQUES",
      "011": "PEDRO ESCOBEDO",
      "012": "PEÑAMILLER",
      "013": "PINAL DE AMOLES",
      "014": "QUERETARO",
      "015": "SAN JOAQUIN",
      "016": "SAN JUAN DEL RIO",
      "017": "TEQUISQUIAPAN",
      "018": "TOLIMAN"
    },
    "23": {
      "001": "BENITO JUAREZ",
      "002": "COZUMEL",
      "003": "FELIPE CARRILLO PUERTO",
      "004": "ISLA MUJERES",
      "005": "JOSE MARIA MORELOS",
      "006": "LAZARO CARDENAS",
      "007": "OTHON P. BLANCO",
      "008": "SOLIDARIDAD",
      "009": "TULUM",
      "010": "BACALAR",
      "011": "PUERTO MORELOS"
    },
    "24": {
      "001": "AHUALULCO",
      "002": "ALAQUINES",
      "003": "AQUISMON",
      "004": "ARMADILLO DE LOS INFANTE",
      "005": "CARDENAS",
      "006": "CATORCE",
      "007": "CEDRAL",
      "008": "CERRITOS",
      "009": "CERRO DE SAN PEDRO",
      "010": "CIUDAD DEL MAIZ",
      "011": "CIUDAD FERNANDEZ",
      "012": "TANCANHUITZ",
      "013": "CIUDAD VALLES",
      "014": "COXCATLAN",
      "015": "CHARCAS",
      "016": "EBANO",
      "017": "GUADALCAZAR",
      "018": "HUEHUETLAN",
      "019": "LAGUNILLAS",
      "020": "MATEHUALA",
      "021": "MEXQUITIC DE CARMONA",
      "022": "MOCTEZUMA",
      "023": "RAYON",
      "024": "RIOVERDE",
      "025": "SALINAS",
      "026": "SAN ANTONIO",
      "027": "SAN CIRO DE ACOSTA",
      "028": "SAN LUIS POTOSI",
      "029": "SAN MARTIN CHALCHICUAUTLA",
      "030": "SAN NICOLAS TOLENTINO",
      "031": "SAN VICENTE TANCUAYALAB",
      "032": "SANTA CATARINA",
      "033": "SANTA MARIA DEL RIO",
      "034": "SANTO DOMINGO",
      "035": "SOLEDAD DE GRACIANO SANCHEZ",
      "036": "TAMASOPO",
      "037": "TAMAZUNCHALE",
      "038": "TAMPACAN",
      "039": "TAMPAMOLON CORONA",
      "040": "TAMUIN",
      "041": "TANLAJAS",
      "042": "TANQUIAN DE ESCOBEDO",
      "043": "TIERRA NUEVA",
      "044": "VANEGAS",
      "045": "VENADO",
      "046": "VILLA DE ARISTA",
      "047": "VILLA DE ARRIAGA",
      "048": "VILLA DE GUADALUPE",
      "049": "VILLA DE LA PAZ",
      "050": "VILLA DE RAMOS",
      "051": "VILLA DE REYES",
      "052": "VILLA HIDALGO",
      "053": "VILLA JUAREZ",
      "054": "AXTLA DE TERRAZAS",
      "055": "XILITLA",
      "056": "ZARAGOZA",
      "057": "EL NARANJO",
      "058": "MATLAPA"
    },
    "25": {
      "001": "AHOME",
      "002": "ANGOSTURA",
      "003": "BADIRAGUATO",
      "004": "CONCORDIA",
      "005": "COSALA",
      "006": "CULIACAN",
      "007": "CHOIX",
      "008": "ELOTA",
      "009": "ESCUINAPA",
      "010": "EL FUERTE",
      "011": "GUASAVE",
      "012": "MAZATLAN",
      "013": "MOCORITO",
      "014": "ROSARIO",
      "015": "SALVADOR ALVARADO",
      "016": "SAN IGNACIO",
      "017": "SINALOA",
      "018": "NAVOLATO"
    },
    "26": {
      "001": "ACONCHI",
      "002": "AGUA PRIETA",
      "003": "ALTAR",
      "004": "ARIVECHI",
      "005": "ARIZPE",
      "006": "ATIL",
      "007": "BACADEHUACHI",
      "008": "BACANORA",
      "009": "BACERAC",
      "010": "BACOACHI",
      "011": "BANAMICHI",
      "012": "BAVIACORA",
      "013": "BAVISPE",
      "014": "BENJAMIN HILL",
      "015": "CANANEA",
      "016": "CUCURPE",
      "017": "CUMPAS",
      "018": "DIVISADEROS",
      "019": "FRONTERAS",
      "020": "GRANADOS",
      "021": "HUACHINERA",
      "022": "HUASABAS",
      "023": "HUEPAC",
      "024": "IMURIS",
      "025": "MAGDALENA",
      "026": "MOCTEZUMA",
      "027": "NACO",
      "028": "NACORI CHICO",
      "029": "NACOZARI DE GARCIA",
      "030": "NOGALES",
      "031": "OQUITOA",
      "032": "SAHUARIPA",
      "033": "SAN FELIPE DE JESUS",
      "034": "SAN JAVIER",
      "035": "SAN PEDRO DE LA CUEVA",
      "036": "SANTA ANA",
      "037": "SANTA CRUZ",
      "038": "SARIC",
      "039": "SOYOPA",
      "040": "SUAQUI GRANDE",
      "041": "TEPACHE",
      "042": "TRINCHERAS",
      "043": "TUBUTAMA",
      "044": "VILLA HIDALGO",
      "045": "VILLA PESQUEIRA",
      "046": "CABORCA",
      "047": "CARBO",
      "048": "LA COLORADA",
      "049": "HERMOSILLO",
      "050": "MAZATAN",
      "051": "OPODEPE",
      "052": "PITIQUITO",
      "053": "PUERTO PEÑASCO",
      "054": "RAYON",
      "055": "SAN LUIS RIO COLORADO",
      "056": "SAN MIGUEL DE HORCASITAS",
      "057": "URES",
      "058": "BACUM",
      "059": "CAJEME",
      "060": "EMPALME",
      "061": "GUAYMAS",
      "062": "ALAMOS",
      "063": "ETCHOJOA",
      "064": "HUATABAMPO",
      "065": "NAVOJOA",
      "066": "ONAVAS",
      "067": "QUIRIEGO",
      "068": "ROSARIO",
      "069": "YECORA",
      "070": "GENERAL PLUTARCO ELIAS CALLES",
      "071": "BENITO JUAREZ",
      "072": "SAN IGNACIO RIO MUERTO"
    },
    "27": {
      "001": "BALANCAN",
      "002": "CARDENAS",
      "003": "CENTLA",
      "004": "CENTRO",
      "005": "COMALCALCO",
      "006": "CUNDUACAN",
      "007": "EMILIANO ZAPATA",
      "008": "HUIMANGUILLO",
      "009": "JALAPA",
      "010": "JALPA DE MENDEZ",
      "011": "JONUTA",
      "012": "MACUSPANA",
      "013": "NACAJUCA",
      "014": "PARAISO",
      "015": "TACOTALPA",
      "016": "TEAPA",
      "017": "TENOSIQUE"
    },
    "28": {
      "001": "ABASOLO",
      "002": "ALDAMA",
      "003": "ALTAMIRA",
      "004": "ANTIGUO MORELOS",
      "005": "BURGOS",
      "006": "BUSTAMANTE",
      "007": "CAMARGO",
      "008": "CASAS",
      "009": "CIUDAD MADERO",
      "010": "CRUILLAS",
      "011": "GOMEZ FARIAS",
      "012": "GONZALEZ",
      "013": "GÜEMEZ",
      "014": "GUERRERO",
      "015": "GUSTAVO DIAZ ORDAZ",
      "016": "HIDALGO",
      "017": "JAUMAVE",
      "018": "JIMENEZ",
      "019": "LLERA",
      "020": "MAINERO",
      "021": "EL MANTE",
      "022": "MATAMOROS",
      "023": "MENDEZ",
      "024": "MIER",
      "025": "MIGUEL ALEMAN",
      "026": "MIQUIHUANA",
      "027": "NUEVO LAREDO",
      "028": "NUEVO MORELOS",
      "029": "OCAMPO",
      "030": "PADILLA",
      "031": "PALMILLAS",
      "032": "REYNOSA",
      "033": "RIO BRAVO",
      "034": "SAN CARLOS",
      "035": "SAN FERNANDO",
      "036": "SAN NICOLAS",
      "037": "SOTO LA MARINA",
      "038": "TAMPICO",
      "039": "TULA",
      "040": "VALLE HERMOSO",
      "041": "VICTORIA",
      "042": "VILLAGRAN",
      "043": "XICOTENCATL"
    },
    "29": {
      "001": "AMAXAC DE GUERRERO",
      "002": "APETATITLAN DE ANTONIO CARVAJAL",
      "003": "APIZACO",
      "004": "ATLANGATEPEC",
      "005": "ATLTZAYANCA",
      "006": "CALPULALPAN",
      "007": "EL CARMEN TEQUEXQUITLA",
      "008": "CUAPIAXTLA",
      "009": "CUAXOMULCO",
      "010": "CHIAUTEMPAN",
      "011": "MUÑOZ DE DOMINGO ARENAS",
      "012": "ESPAÑITA",
      "013": "HUAMANTLA",
      "014": "HUEYOTLIPAN",
      "015": "IXTACUIXTLA DE MARIANO MATAMOROS",
      "016": "IXTENCO",
      "017": "MAZATECOCHCO DE JOSE MARIA MORELOS",
      "018": "CONTLA DE JUAN CUAMATZI",
      "019": "TEPETITLA DE LARDIZABAL",
      "020": "SANCTORUM DE LAZARO CARDENAS",
      "021": "NANACAMILPA DE MARIANO ARISTA",
      "022": "ACUAMANALA DE MIGUEL HIDALGO",
      "023": "NATIVITAS",
      "024": "PANOTLA",
      "025": "SAN PABLO DEL MONTE",
      "026": "SANTA CRUZ TLAXCALA",
      "027": "TENANCINGO",
      "028": "TEOLOCHOLCO",
      "029": "TEPEYANCO",
      "030": "TERRENATE",
      "031": "TETLA DE LA SOLIDARIDAD",
      "032": "TETLATLAHUCA",
      "033": "TLAXCALA",
      "034": "TLAXCO",
      "035": "TOCATLAN",
      "036": "TOTOLAC",
      "037": "ZITLALTEPEC DE TRINIDAD SANCHEZ SANTOS",
      "038": "TZOMPANTEPEC",
      "039": "XALOZTOC",
      "040": "XALTOCAN",
      "041": "PAPALOTLA DE XICOHTENCATL",
      "042": "XICOHTZINCO",
      "043": "YAUHQUEMEHCAN",
      "044": "ZACATELCO",
      "045": "SANTA APOLONIA TEACALCO",
      "046": "SANTA CRUZ QUILEHTLA",
      "047": "SAN JUAN HUACTZINCO",
      "048": "SANTA CATARINA AYOMETLA",
      "049": "SANTA ISABEL XILOXOXTLA",
      "050": "SAN JOSE TEACALCO",
      "051": "SAN FRANCISCO TETLANOHCAN",
      "052": "LA MAGDALENA TLALTELULCO",
      "053": "SAN DAMIAN TEXOLOC",
      "054": "EMILIANO ZAPATA",
      "055": "LAZARO CARDENAS",
      "056": "SAN JERONIMO ZACUALPAN",
      "057": "SAN LUCAS TECOPILCO",
      "058": "SANTA ANA NOPALUCAN",
      "059": "SAN LORENZO AXOCOMANITLA",
      "060": "BENITO JUAREZ"
    },
    "30": {
      "001": "ACAJETE",
      "002": "ACATLAN",
      "003": "ACAYUCAN",
      "004": "ACTOPAN",
      "005": "ACULA",
      "006": "ACULTZINGO",
      "007": "CAMARON DE TEJEDA",
      "008": "ALAMO TEMAPACHE",
      "009": "ALPATLAHUAC",
      "010": "ALTO LUCERO DE GUTIERREZ BARRIOS",
      "011": "ALTOTONGA",
      "012": "ALVARADO",
      "013": "AMATITLAN",
      "014": "AMATLAN DE LOS REYES",
      "015": "NARANJOS AMATLAN",
      "016": "ANGEL R. CABADA",
      "017": "LA ANTIGUA",
      "018": "APAZAPAN",
      "019": "AQUILA",
      "020": "ASTACINGA",
      "021": "ATLAHUILCO",
      "022": "ATOYAC",
      "023": "ATZACAN",
      "024": "ATZALAN",
      "025": "TLALTETELA",
      "026": "AYAHUALULCO",
      "027": "BANDERILLA",
      "028": "BENITO JUAREZ",
      "029": "BOCA DEL RIO",
      "030": "CALCAHUALCO",
      "031": "CAMERINO Z. MENDOZA",
      "032": "CARRILLO PUERTO",
      "033": "CASTILLO DE TEAYO",
      "034": "CATEMACO",
      "035": "CAZONES DE HERRERA",
      "036": "CERRO AZUL",
      "037": "CITLALTEPETL",
      "038": "COACOATZINTLA",
      "039": "COAHUITLAN",
      "040": "COATEPEC",
      "041": "COATZACOALCOS",
      "042": "COATZINTLA",
      "043": "COETZALA",
      "044": "COLIPA",
      "045": "COMAPA",
      "046": "CORDOBA",
      "047": "COSAMALOAPAN",
      "048": "COSAUTLAN DE CARVAJAL",
      "049": "COSCOMATEPEC",
      "050": "COSOLEACAQUE",
      "051": "COTAXTLA",
      "052": "COXQUIHUI",
      "053": "COYUTLA",
      "054": "CUICHAPA",
      "055": "CUITLAHUAC",
      "056": "CHACALTIANGUIS",
      "057": "CHALMA",
      "058": "CHICONAMEL",
      "059": "CHICONQUIACO",
      "060": "CHICONTEPEC",
      "061": "CHINAMECA",
      "062": "CHINAMPA DE GOROSTIZA",
      "063": "LAS CHOAPAS",
      "064": "CHOCAMAN",
      "065": "CHONTLA",
      "066": "CHUMATLAN",
      "067": "EMILIANO ZAPATA",
      "068": "ESPINAL",
      "069": "FILOMENO MATA",
      "070": "FORTIN",
      "071": "GUTIERREZ ZAMORA",
      "072": "HIDALGOTITLAN",
      "073": "HUATUSCO",
      "074": "HUAYACOCOTLA",
      "075": "HUEYAPAN DE OCAMPO",
      "076": "HUILOAPAN DE CUAUHTEMOC",
      "077": "IGNACIO DE LA LLAVE",
      "078": "ILAMATLAN",
      "079": "ISLA",
      "080": "IXCATEPEC",
      "081": "IXHUACAN DE LOS REYES",
      "082": "IXHUATLAN DE MADERO",
      "083": "IXHUATLAN DEL CAFE",
      "084": "IXHUATLAN DEL SURESTE",
      "085": "IXHUATLANCILLO",
      "086": "IXMATLAHUACAN",
      "087": "IXTACZOQUITLAN",
      "088": "JALACINGO",
      "089": "XALAPA",
      "090": "JALCOMULCO",
      "091": "JALTIPAN",
      "092": "JAMAPA",
      "093": "JESUS CARRANZA",
      "094": "JILOTEPEC",
      "095": "JUAN RODRIGUEZ CLARA",
      "096": "JUCHIQUE DE FERRER",
      "097": "LANDERO Y COSS",
      "098": "LERDO DE TEJADA",
      "099": "MAGDALENA",
      "100": "MALTRATA",
      "101": "MANLIO FABIO ALTAMIRANO",
      "102": "MARIANO ESCOBEDO",
      "103": "MARTINEZ DE LA TORRE",
      "104": "MECATLAN",
      "105": "MECAYAPAN",
      "106": "MEDELLIN DE BRAVO",
      "107": "MIAHUATLAN",
      "108": "LAS MINAS",
      "109": "MINATITLAN",
      "110": "MISANTLA",
      "111": "MIXTLA DE ALTAMIRANO",
      "112": "MOLOACAN",
      "113": "NAOLINCO",
      "114": "NARANJAL",
      "115": "NAUTLA",
      "116": "NOGALES",
      "117": "OLUTA",
      "118": "OMEALCA",
      "119": "ORIZABA",
      "120": "OTATITLAN",
      "121": "OTEAPAN",
      "122": "OZULUAMA",
      "123": "PAJAPAN",
      "124": "PANUCO",
      "125": "PAPANTLA",
      "126": "PASO DEL MACHO",
      "127": "PASO DE OVEJAS",
      "128": "LA PERLA",
      "129": "PEROTE",
      "130": "PLATON SANCHEZ",
      "131": "PLAYA VICENTE",
      "132": "POZA RICA DE HIDALGO",
      "133": "PUEBLO VIEJO",
      "134": "PUENTE NACIONAL",
      "135": "RAFAEL DELGADO",
      "136": "RAFAEL LUCIO",
      "137": "LAS VIGAS DE RAMIREZ",
      "138": "LOS REYES",
      "139": "RIO BLANCO",
      "140": "SALTABARRANCA",
      "141": "SAN ANDRES TENEJAPAN",
      "142": "SAN ANDRES TUXTLA",
      "143": "SAN JUAN EVANGELISTA",
      "144": "SANTIAGO TUXTLA",
      "145": "SAYULA DE ALEMAN",
      "146": "SOCONUSCO",
      "147": "SOCHIAPA",
      "148": "SOLEDAD ATZOMPA",
      "149": "SOLEDAD DE DOBLADO",
      "150": "SOTEAPAN",
      "151": "TAMALIN",
      "152": "TAMIAHUA",
      "153": "TAMPICO ALTO",
      "154": "TANCOCO",
      "155": "TANTIMA",
      "156": "TANTOYUCA",
      "157": "TATATILA",
      "158": "TECOLUTLA",
      "159": "TEHUIPANGO",
      "160": "TEMPOAL",
      "161": "TENAMPA",
      "162": "TENOCHTITLAN",
      "163": "TEOCELO",
      "164": "TEPATLAXCO",
      "165": "TEPETLAN",
      "166": "TEPETZINTLA",
      "167": "TEQUILA",
      "168": "JOSE AZUETA",
      "169": "TEXCATEPEC",
      "170": "TEXHUACAN",
      "171": "TEXISTEPEC",
      "172": "TEZONAPA",
      "173": "TIERRA BLANCA",
      "174": "TIHUATLAN",
      "175": "TLACOJALPAN",
      "176": "TLACOLULAN",
      "177": "TLACOTALPAN",
      "178": "TLACOTEPEC DE MEJIA",
      "179": "TLACHICHILCO",
      "180": "TLALIXCOYAN",
      "181": "TLALNELHUAYOCAN",
      "182": "TLAPACOYAN",
      "183": "TLAQUILPA",
      "184": "TLILAPAN",
      "185": "TOMATLAN",
      "186": "TONAYAN",
      "187": "TOTUTLA",
      "188": "TUXPAN",
      "189": "TUXTILLA",
      "190": "URSULO GALVAN",
      "191": "VEGA DE ALATORRE",
      "192": "VERACRUZ",
      "193": "VILLA ALDAMA",
      "194": "XICO",
      "195": "XOXOCOTLA",
      "196": "YANGA",
      "197": "YECUATLA",
      "198": "ZACUALPAN",
      "199": "ZARAGOZA",
      "200": "ZENTLA",
      "201": "ZONGOLICA",
      "202": "ZONTECOMATLAN",
      "203": "ZOZOCOLCO DE HIDALGO",
      "204": "TRES VALLES",
      "205": "NANCHITAL DE LAZARO CARDENAS DEL RIO",
      "206": "AGUA DULCE",
      "207": "EL HIGO",
      "208": "CARLOS A. CARRILLO",
      "209": "UXPANAPA",
      "210": "TATAHUICAPAN DE JUAREZ",
      "211": "SAN RAFAEL",
      "212": "SANTIAGO SOCHIAPAN"
    },
    "31": {
      "001": "ABALA",
      "002": "ACANCEH",
      "003": "AKIL",
      "004": "BACA",
      "005": "BOKOBA",
      "006": "BUCTZOTZ",
      "007": "CACALCHEN",
      "008": "CALOTMUL",
      "009": "CANSAHCAB",
      "010": "CANTAMAYEC",
      "011": "CELESTUN",
      "012": "CENOTILLO",
      "013": "CONKAL",
      "014": "CUNCUNUL",
      "015": "CUZAMA",
      "016": "CHACSINKIN",
      "017": "CHANKOM",
      "018": "CHAPAB",
      "019": "CHEMAX",
      "020": "CHICXULUB PUEBLO",
      "021": "CHICHIMILA",
      "022": "CHIKINDZONOT",
      "023": "CHOCHOLA",
      "024": "CHUMAYEL",
      "025": "DZAN",
      "026": "DZEMUL",
      "027": "DZIDZANTUN",
      "028": "DZILAM DE BRAVO",
      "029": "DZILAM GONZALEZ",
      "030": "DZITAS",
      "031": "DZONCAUICH",
      "032": "ESPITA",
      "033": "HALACHO",
      "034": "HOCABA",
      "035": "HOCTUN",
      "036": "HOMUN",
      "037": "HUHI",
      "038": "HUNUCMA",
      "039": "IXIL",
      "040": "IZAMAL",
      "041": "KANASIN",
      "042": "KANTUNIL",
      "043": "KAUA",
      "044": "KINCHIL",
      "045": "KOPOMA",
      "046": "MAMA",
      "047": "MANI",
      "048": "MAXCANU",
      "049": "MAYAPAN",
      "050": "MERIDA",
      "051": "MOCOCHA",
      "052": "MOTUL",
      "053": "MUNA",
      "054": "MUXUPIP",
      "055": "OPICHEN",
      "056": "OXKUTZCAB",
      "057": "PANABA",
      "058": "PETO",
      "059": "PROGRESO",
      "060": "QUINTANA ROO",
      "061": "RIO LAGARTOS",
      "062": "SACALUM",
      "063": "SAMAHIL",
      "064": "SANAHCAT",
      "065": "SAN FELIPE",
      "066": "SANTA ELENA",
      "067": "SEYE",
      "068": "SINANCHE",
      "069": "SOTUTA",
      "070": "SUCILA",
      "071": "SUDZAL",
      "072": "SUMA",
      "073": "TAHDZIU",
      "074": "TAHMEK",
      "075": "TEABO",
      "076": "TECOH",
      "077": "TEKAL DE VENEGAS",
      "078": "TEKANTO",
      "079": "TEKAX",
      "080": "TEKIT",
      "081": "TEKOM",
      "082": "TELCHAC PUEBLO",
      "083": "TELCHAC PUERTO",
      "084": "TEMAX",
      "085": "TEMOZON",
      "086": "TEPAKAN",
      "087": "TETIZ",
      "088": "TEYA",
      "089": "TICUL",
      "090": "TIMUCUY",
      "091": "TINUM",
      "092": "TIXCACALCUPUL",
      "093": "TIXKOKOB",
      "094": "TIXMEHUAC",
      "095": "TIXPEHUAL",
      "096": "TIZIMIN",
      "097": "TUNKAS",
      "098": "TZUCACAB",
      "099": "UAYMA",
      "100": "UCU",
      "101": "UMAN",
      "102": "VALLADOLID",
      "103": "XOCCHEL",
      "104": "YAXCABA",
      "105": "YAXKUKUL",
      "106": "YOBAIN"
    },
    "32": {
      "001": "APOZOL",
      "002": "APULCO",
      "003": "ATOLINGA",
      "004": "BENITO JUAREZ",
      "005": "CALERA",
      "006": "CAÑITAS DE FELIPE PESCADOR",
      "007": "CONCEPCION DEL ORO",
      "008": "CUAUHTEMOC",
      "009": "CHALCHIHUITES",
      "010": "FRESNILLO",
      "011": "TRINIDAD GARCIA DE LA CADENA",
      "012": "GENARO CODINA",
      "013": "GENERAL ENRIQUE ESTRADA",
      "014": "GENERAL FRANCISCO R. MURGUIA",
      "015": "EL PLATEADO DE JOAQUIN AMARO",
      "016": "GENERAL PANFILO NATERA",
      "017": "GUADALUPE",
      "018": "HUANUSCO",
      "019": "JALPA",
      "020": "JEREZ",
      "021": "JIMENEZ DEL TEUL",
      "022": "JUAN ALDAMA",
      "023": "JUCHIPILA",
      "024": "LORETO",
      "025": "LUIS MOYA",
      "026": "MAZAPIL",
      "027": "MELCHOR OCAMPO",
      "028": "MEZQUITAL DEL ORO",
      "029": "MIGUEL AUZA",
      "030": "MOMAX",
      "031": "MONTE ESCOBEDO",
      "032": "MORELOS",
      "033": "MOYAHUA DE ESTRADA",
      "034": "NOCHISTLAN DE MEJIA",
      "035": "NORIA DE ANGELES",
      "036": "OJOCALIENTE",
      "037": "PANUCO",
      "038": "PINOS",
      "039": "RIO GRANDE",
      "040": "SAIN ALTO",
      "041": "EL SALVADOR",
      "042": "SOMBRERETE",
      "043": "SUSTICACAN",
      "044": "TABASCO",
      "045": "TEPECHITLAN",
      "046": "TEPETONGO",
      "047": "TEUL DE GONZALEZ ORTEGA",
      "048": "TLALTENANGO DE SANCHEZ ROMAN",
      "049": "VALPARAISO",
      "050": "VETAGRANDE",
      "051": "VILLA DE COS",
      "052": "VILLA GARCIA",
      "053": "VILLA GONZALEZ ORTEGA",
      "054": "VILLA HIDALGO",
      "055": "VILLANUEVA",
      "056": "ZACATECAS",
      "057": "TRANCOSO",
      "058": "SANTA MARIA DE LA PAZ"
    }
  };

export {
    GenderData,
    months,
    states,
    municipalities,
}